### ISSUE TITLE
[Doc] Translate the design document (schema-registry.md)

### ISSUE THREAD

**Issue by kirinzhu** [apache/eventmesh#1065]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

Please translate the docs/en/design-document/04-schema-registry.md (English version) into docs/zh/design-document/04-schema-registry.md (Chinese version).
By doing so, you can get a deeper understanding about the workflow module in EventMesh.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by vinayakghatul** [comment]
please assign this to me!

**Comment by yashchaddha** [comment]
I would like to work on this issue, hence would like to request for it to be assigned to me 
Thanks in advance
