### ISSUE TITLE
[Doc] Translate the design document (tracing.md)

### ISSUE THREAD

**Issue by kirinzhu** [apache/eventmesh#1069]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

Please translate the docs/en/design-document/07-tracing.md (English version) into docs/zh/design-document/07-tracing.md (Chinese version).
By doing so, you can get a deeper understanding about the workflow module in EventMesh.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by vinayakghatul** [comment]
please assign this to me!

**Comment by hanshal101** [comment]
please assign me this task I'll complete it

**Comment by luahan77m** [comment]
Hi, I'm new to open source and want to try to solve some simple problems. Can you assign this issue to me? I would appreciate it!
