### ISSUE TITLE
[Enhancement] Eventmesh server go deployments

### ISSUE THREAD

**Issue by walleliu1016** [apache/eventmesh#1133]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Write eventmesh docker-compose and helms config file, used to boot eventmesh server go quickly.

### Describe the solution you'd like

You can refers Dockerfile in the java project.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
Since the parent issue has been closed, no further resources will be allocated for the development of this issue for a certain period of time.
