### ISSUE TITLE
[Enhancement] eventmesh server go plugin

### ISSUE THREAD

**Issue by walterlife** [apache/eventmesh#1139]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Complete the plugin module(include log,naming,database,config)

### Describe the solution you'd like

implement a pluggable architecture

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh/pull/1140
