### ISSUE TITLE
[Feature] EventBus dashboard

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#1147]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

- [ ] define event source
- [ ] define event bus
- [ ] define event filter
- [ ] define event transform
- [ ] define event target

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wuyiliang1** [comment]
I want to work on this, can you assign this to me?

**Comment by qqeasonchen** [comment]
> I want to work on this, can you assign this to me? 

sure

**Comment by Pil0tXia** [comment]
Superseded by https://github.com/apache/eventmesh/issues/4400
