### ISSUE TITLE
[Doc] Document retranslation editing [01-prometheus.md 02-zipkin.md] 

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#1177]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

Located at:
docs/zh/design-document/11-prometheus.md
docs/zh/design-document/12-zipkin.md
Chinese version 11-prometheus.md and 12-zipkin.md are out of date, please re-translate and edit according to English version.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 847850277** [comment]
i want to try , please asign to me .

**Comment by Alonexc** [comment]
> i want to try , please asign to me .
Of course, you can submit a pr first.

**Comment by hanshal101** [comment]
Please assign me this issue I have already made a PR

**Comment by hanshal101** [comment]
please assign me this task

**Comment by Alonexc** [comment]
@hanshal101 You can submit your pr first and associate this issue.
