### ISSUE TITLE
[Enhancement] Fix the Kafka Consumer

### ISSUE THREAD

**Issue by Markliniubility** [apache/eventmesh#1205]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

The Kafka Consumer is not yet fully implemented

### Describe the solution you'd like

Implement the Kafka Consumer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
Completed.
