### ISSUE TITLE
[Enhancement] auto publish docker images

### ISSUE THREAD

**Issue by RiESAEX** [apache/eventmesh#1206]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

use github action to auto publish docker image.

### Describe the solution you'd like

Question:
Should the docker image include the java source code? 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
@RiESAEX how is going for this?

**Comment by RiESAEX** [comment]
https://hub.docker.com/repository/docker/xwbx/eventmesh
https://github.com/RiESAEX/incubator-eventmesh/tree/publishdocker2
I tried to run my images, but with no luck.

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh/pull/4282 and https://github.com/apache/eventmesh/pull/4675
