### ISSUE TITLE
[Bug] HTTP protocol when multiple consumers use the same ConsumerGroup, the EventMeshConsumer Topic status is inconsistent ?

### ISSUE THREAD

**Issue by ruanjf** [apache/eventmesh#1263]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

refresh consumer group do not update EventMeshConsumer.consumerGroupConfig. Causes verification of topic to fail?

1. subscription change for `Subscribe`,`Unsubscribe`
https://github.com/apache/incubator-eventmesh/blob/f6aefd75e8ca80d58a6a6e5b188b2b78ba46c449/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerManager.java#L180-L210

1. consumer group state change
https://github.com/apache/incubator-eventmesh/blob/f6aefd75e8ca80d58a6a6e5b188b2b78ba46c449/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerManager.java#L322-L342

1. refresh consumer group do not update `EventMeshConsumer.consumerGroupConfig`
https://github.com/apache/incubator-eventmesh/blob/f6aefd75e8ca80d58a6a6e5b188b2b78ba46c449/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerGroupManager.java#L70-L83

1. check topic when consume message (fail)
https://github.com/apache/incubator-eventmesh/blob/f6aefd75e8ca80d58a6a6e5b188b2b78ba46c449/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java#L125-L138

### How to reproduce

Start multiple consumers use the same ConsumerGroup

### Debug logs

no topicConfig found, consumerGroup:test-group topic:test

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
@ruanjf welcome to fix it~

**Comment by Pil0tXia** [comment]
@ruanjf May you please help submit a bugfix PR if this bug still exists? I would greatly appreciate it for that.

**Comment by ruanjf** [comment]
@Pil0tXia Can't reproduce now

**Comment by Pil0tXia** [comment]
Thanks for your verification! Then I will close this issue as completed. Please feel free to reopen it if you have something more to share with us.
