### ISSUE TITLE
[Enhancement] Add Code Conduct for pr submmit

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#1450]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

There is a lack of a Code Conduct for issue and pr template whenever a new issue or pr was submitted.

### Describe the solution you'd like

The contributor needs to agree[1] whenever he(she) submit a new issue or pr.
[1]https://www.apache.org/foundation/policies/conduct

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
Completed.
