### ISSUE TITLE
 Possible null pointer dereference due to return value of called method [SyncResponse]

### ISSUE THREAD

**Issue by yangxihong** [apache/eventmesh#1888]
![企业微信截图_16667763194136](https://user-images.githubusercontent.com/26154304/197989825-a9c31f99-e1d3-4d30-8f6b-e9e86fb87244.png)

located at:
org/apache/eventmesh/tcp/demo/sub/cloudevents/SyncResponse.java line 74
Add NPE to check for exceptions.

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh/pull/1910
