### ISSUE TITLE
[Enhancement][WIP]EventMesh integrates OpenFunction as its Async Framework proposal 

### ISSUE THREAD

**Issue by walterlife** [apache/eventmesh#2040]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

WIP

### Describe the solution you'd like

WIP

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
@walterlife good proposal, and welcome other guys to join in together.

**Comment by benjaminhuo** [comment]
OpenFunction maintainer here, glad to work together with the EventMesh community! 
@wanjunlei @wrongerror @webup @lizzzcai @tpiperatgod

**Comment by qqeasonchen** [comment]
> OpenFunction maintainer here, glad to work together with the EventMesh community! @wanjunlei @wrongerror @webup @lizzzcai @tpiperatgod

Glad to see you guys :), looking forward to it.

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh/pull/4124.
