### ISSUE TITLE
Use the {} tag to inject dynamic content into the string [WatchFileManager]

### ISSUE THREAD

**Issue by yongxizhai** [apache/eventmesh#2156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Use the {} tag to inject dynamic content into the string [WatchFileManager]

### Describe the solution you'd like

Use the {} tag to inject dynamic content into the string [WatchFileManager]

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
Completed in current code.
