### ISSUE TITLE
[Question] I cannot find c++ or c sdk 

### ISSUE THREAD

**Issue by loveslikey** [apache/eventmesh#2174]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

Looking at the architecture diagram, it supports calling the api called by c, but I didn't find it

**Comment by qqeasonchen** [comment]
yes, it is not open source yet, do you need it？

**Comment by loveslikey** [comment]
Yes, a heterogeneous system recently required it，can you provide me with a reference?

**Comment by qqeasonchen** [comment]
> Yes, a heterogeneous system recently required it，can you provide me with a reference?

sure, you can join wechat assistant

**Comment by qqeasonchen** [comment]
@loveslikey do you still here?

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh/issues/4318.
