### ISSUE TITLE
[Enhancement] Method passes a concatenated string to SLF4J's or Log4j2's format string[RequestContext]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#2976]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/215702484-171d779e-e279-48ed-be85-caedb98d14c5.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/catalog/EventMeshCatalogClient.java line 70
analysis and explanation:
This method concatenates the output of a toString() call into a StringBuffer or StringBuilder. It is simpler just to pass the object you want to append to the append call, as that form does not suffer the potential for NullPointerExceptions, and is easier to read.

### Describe the solution you'd like

remove of .toString to avoid NPE.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by monish-byte** [comment]
hey @Alonexc is this issue closed? because when I checked the code it was already resolved.

**Comment by Alonexc** [comment]
Welcome to your pr.

**Comment by dipankr** [comment]
@Alonexc the changes are already there in the codebase, checked in through : https://github.com/apache/eventmesh/commit/066ae98b7ee05059830f5347178e21e70b8408fe

we can close this.
thanks

**Comment by Alonexc** [comment]
Okay.
