### ISSUE TITLE
[Enhancement] Iteration can be replaced with bulk 'Collection.addAll' call

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#2981]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/215703934-f3fb38b8-18d0-428b-9c06-4114c019bc82.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java line 140

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/215703989-57921600-2c92-4fc2-88fc-d279dfa30564.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nikam14** [comment]
this issue is resolved
![4](https://user-images.githubusercontent.com/55378196/234514864-913e6cf5-3562-4fe3-a0f2-2a3cad2bcb04.PNG)

can be closed.
