### ISSUE TITLE
[Enhancement] Method makes literal string comparisons passing the literal as an argument [RegistryHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3002]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/216218759-7dc00b15-0e8d-4de3-a977-40fe0f97d15a.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RegistryHandler.java line 121,124
analysis and explanation:
This line is in the form of String str = str.equals("someOtherString");
A NullPointerException may occur if the String variable str is null. If instead the code was restructured to String str = "someOtherString".equals(str);that is, call equals() on the string literal, passing the variable as an argument, then this exception could never happen as both equals() check for null.

### Describe the solution you'd like

Adjust the code to String str = "someOtherString".equals(str).

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rottenmu** [comment]
I accept this task

**Comment by Alonexc** [comment]
> I accept this task

@rottenmu Hello, how are you doing with this issue?
