### ISSUE TITLE
[Enhancement] Method manually handles closing an auto-closeable resource [MetaHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3010]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

https://github.com/apache/eventmesh/blob/ee9ee4c63670b57b832898624a061335153bb67c/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/MetaHandler.java#L138-L145
analysis and explanation:
This method allocates and uses an auto closeable resource. However, it manually closes the resource in a finally block. While this is correct management, it doesn't rely on the idiomatic way available to JDK 7 and above, allows for possible subtle problems, and complicates the reading of code by developers expecting the use of try-with-resources.

### Describe the solution you'd like

Change to use try-with-resources to manage resources.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by arsenalzp** [comment]
Is this issue still alive? It seems nobody has been working long time on it. If so I would like to pick it up.

**Comment by Pil0tXia** [comment]
@arsenalzp Welcome!
