### ISSUE TITLE
[Enhancement]  Method manually handles closing an auto-closeable resource [TCPClientHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3011]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/216220309-b71e7e60-8dfd-4f3b-ba1c-6b64b954c1a3.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TCPClientHandler.java line 119,183
analysis and explanation:
This method allocates and uses an auto closeable resource. However, it manually closes the resource in a finally block. While this is correct management, it doesn't rely on the idiomatic way available to JDK 7 and above, allows for possible subtle problems, and complicates the reading of code by developers expecting the use of try-with-resources.

### Describe the solution you'd like

Change to use try-with-resources to manage resources.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nikam14** [comment]
@Alonexc  do you want to change line 84 from this 
![1](https://user-images.githubusercontent.com/55378196/234499481-dee50c99-1dbe-4854-a5a9-8ca228251de1.PNG)
to this
![2](https://user-images.githubusercontent.com/55378196/234499533-8cbb320e-0284-43ed-a4f3-e436a4ba4ec7.PNG)
and remove the finally block at line 117.

correct me if something is wrong.

**Comment by Alonexc** [comment]
Yes, there are already similar modification cases. you can refer to them. #3782
