### ISSUE TITLE
[Enhancement] Method manually handles closing an auto-closeable resource [TopicHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3012]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/216220461-4845705e-517e-49c1-8efb-90551c6dbf12.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TopicHandler.java line 104,141,178
analysis and explanation:
This method allocates and uses an auto closeable resource. However, it manually closes the resource in a finally block. While this is correct management, it doesn't rely on the idiomatic way available to JDK 7 and above, allows for possible subtle problems, and complicates the reading of code by developers expecting the use of try-with-resources.

### Describe the solution you'd like

Change to use try-with-resources to manage resources.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by devCod3r** [comment]
Hi @Alonexc, I would like to work on this issue, please assign it to me if possible. I will submit a PR in a few days.

**Comment by Alonexc** [comment]
Welcome！
