### ISSUE TITLE
[Enhancement] Found reliance on default encoding: String.getBytes() [ConfigurationHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3013]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/216220601-1f48b09e-46a8-4c93-a02d-127266416192.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ConfigurationHandler.java line 107,108,118,119
analysis and explanation:
Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms.

### Describe the solution you'd like

Use an alternative API and specify a charset name or Charset object explicitly.
e.g.
![image](https://user-images.githubusercontent.com/91315508/216492257-c2803b2d-81fa-4d46-83d0-8d43543939d9.png)
eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChelseaChanu** [comment]
I like to work on the issue.
