### ISSUE TITLE
[Enhancement] Confusing argument 'null', unclear if a varargs or non-varargs call is desired.

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218020283-12d56cc8-e74b-4b3c-992d-31547fe2801c.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/convert/converter/ObjectConverter.java line 142,147,191

### Describe the solution you'd like

e.g.
![image](https://user-images.githubusercontent.com/91315508/218020352-179935c3-8166-412d-a1e4-bc2ad086f798.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nikam14** [comment]
This issue is resolved. ISSUE#3083 can be closed
![issue](https://user-images.githubusercontent.com/55378196/234485504-5dc7f870-7f49-4555-85ad-9d23713b74f7.PNG)

line 146.
