### ISSUE TITLE
[Enhancement] Method invocation may produce 'NullPointerException'[MessageUtils]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3095]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218023791-1c2ff330-9830-463c-8b18-783c324e1be7.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/MessageUtils.java line 85,91

### Describe the solution you'd like

e.g.
![image](https://user-images.githubusercontent.com/91315508/218023820-82cb02b6-19ae-4be6-8818-93b8f38290c3.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jjbiggins** [comment]
created pull request for #3096; I commit changes for this there.

**Comment by Pil0tXia** [comment]
> created pull request for #3096; I commit changes for this there.

No changes were found in https://github.com/apache/eventmesh/pull/3135 to fix this issue. This issue is unfixed and open for contribution.

**Comment by cnzakii** [comment]
@Pil0tXia 
This seems like an easy job, I wonder if I could be assigned it? 🫣

**Comment by Pil0tXia** [comment]
@cnzakii Of course
