### ISSUE TITLE
[Enhancement] Lambda can be replaced with method reference

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3099]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218024284-a4b4f960-4d1f-4e85-8fea-84459ef82a50.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java line 214

### Describe the solution you'd like

e.g.
![image](https://user-images.githubusercontent.com/91315508/218024326-d491a702-b5a5-4cbc-ad34-9d01f56291d4.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
This issue is open for contribution.

**Comment by cnzakii** [comment]
@Pil0tXia 

This issue has been fixed

![image](https://github.com/apache/eventmesh/assets/91261012/3377e243-bfc3-49f2-bad1-3503595b777c)
