### ISSUE TITLE
[Enhancement] Reliance on default encoding[RedirectClientByPathHandlerTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3159]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/219285846-ac904073-24f2-4b69-8091-e2aa42d3aba9.png)
located at:
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientByPathHandlerTest.java line 127
analysis and explanation:
Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/219285870-cd850001-3fa4-4cb4-893f-d201c25c7ef2.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by devCod3r** [comment]
Hi @Alonexc,  Is it possible that I can work on this issue? I am a beginner to Open Source, and this will be my first issue to work on if I get a chance.

**Comment by Alonexc** [comment]
@devCod3r Of course, you can submit a pr first, welcome to the eventmesh community.
