### ISSUE TITLE
[Question] What is the usage of EventMeshVersion?

### ISSUE THREAD

**Issue by ileonli** [apache/eventmesh#3205]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

[EventMeshVersion](https://github.com/apache/incubator-eventmesh/blob/8c1cb3d69f3dfbbf581c78cbaf81cdb240c0acf7/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/constants/EventMeshVersion.java#L30) class have a Version enum, and current version is 3.0.0.

```Java
public enum Version {
    V3_0_0,
    V3_0_1,
    V3_1_0,
    V3_2_0,
    V3_3_0
}
```

```Java
public static final String CURRENT_VERSION = Version.V3_0_0.name();
```

 I checked the git history, I found it has a long time not to update. Did we forget to update it? Does it still work?

Looking forward to your reply, thanks.

**Comment by pandaapo** [comment]
It will be updated if this pr #4055 can be merged.
