### ISSUE TITLE
[Enhancement] upgrade Gradle 7.6 to 8.x

### ISSUE THREAD

**Issue by jonyangx** [apache/eventmesh#3245]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

upgrade Gradle 7.6 to 8.x

### Describe the solution you'd like

upgrade gradle version to 8.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
Completed.
