### ISSUE TITLE
[Enhancement] Added token-based ACL authentication, about Subscriber

### ISSUE THREAD

**Issue by slowpao** [apache/eventmesh#3309]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Describe the solution you'd like

Supports token-based authentication to verify the token string in the request

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh/pull/3322
