### ISSUE TITLE
[Enhancement] The code processing logic here is the same.

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3388]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224200625-2beecd95-0c8e-4acb-9480-27f66f551ff4.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java line 233-247
analysis and explanation:
If the same logic is truly needed for both instances, then in an if chain they should be combined, or for a switch, one should fall through to the other.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/224200900-71f6a383-aa31-4017-800d-9332ce79b9bc.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kyooosukedn** [comment]
Hi, I would love to submit a PR :)

**Comment by Alonexc** [comment]
@kyooosukedn Welcome to the eventmesh community.
