### ISSUE TITLE
[Enhancement] Do some code optimization.[ClientGroupWrapper]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3394]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224202043-0ff7019d-284e-45a9-9623-ff3c66a606a9.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/224202074-638a9cef-142d-4593-8efd-dc38f08ab504.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by garimellasrisudha** [comment]
Hi Alonexc,

Raised PR for above issue 
https://github.com/apache/eventmesh/pull/3739
