### ISSUE TITLE
[Enhancement] Make field a static final constant or non-public

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3397]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224202339-dc2ca594-3cd2-4e60-b294-90611bfde3de.png)
located at: 
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/DownStreamMsgContext.java

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/224202396-3051674f-9ac8-44c9-9f0b-aa0ca9198bbe.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by garimellasrisudha** [comment]
Hi Alonexc,
is it available ?
if yes could you assign it to me

**Comment by Alonexc** [comment]
@garimellasrisudha Of course, you can submit a pr first, welcome to the eventmesh community.

**Comment by garimellasrisudha** [comment]
thank you Alonexc

**Comment by garimellasrisudha** [comment]
Hi Alonexc,

I raised Pull request for the change.
https://github.com/apache/eventmesh/pull/3701
let me know if any changes required

**Comment by Alonexc** [comment]
@garimellasrisudha It has been commented under the pr you submitted.

**Comment by garimellasrisudha** [comment]
Hi Alonexc ,
Made remaining fields also final ,Could you review and let me know.
Apart from that i tried linking the issue with pull request but, I guess this story i not assigned to  me, that's why i am unable to link .
https://github.com/apache/eventmesh/pull/3738
Thanks sudha
