### ISSUE TITLE
[Enhancement]  Do some code optimization.[EventHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3398]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224202442-845d080b-733b-413b-b52b-24401b5f7b93.png)
![image](https://user-images.githubusercontent.com/91315508/224202455-47d6a071-7a5c-4253-96be-ef6255a73a59.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/EventHandler.java line 83,108

### Describe the solution you'd like

a.return an empty map instead of null
![image](https://user-images.githubusercontent.com/91315508/224202546-1a0a3c23-43ef-41e2-9383-07cbaad9438c.png)

b.remove this "close" call; closing the resource is handled automatically by the try-with-resources.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by garimellasrisudha** [comment]
Hi Alonexc ,
can you assign this to me??

**Comment by Alonexc** [comment]
@garimellasrisudha This issue has already been submitted pr, are you interested in other issues? Your pr is very welcome.
