### ISSUE TITLE
[Enhancement] Do some code optimization.[WebhookPushRequest]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3400]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224203326-f42227c0-350e-4da3-a4a0-132f4195c93e.png)
![image](https://user-images.githubusercontent.com/91315508/224203336-68b7a58e-cd00-4b03-bed4-55e842ec75b2.png)
![image](https://user-images.githubusercontent.com/91315508/224203351-4a281c89-687b-4013-b0c0-c3ce512a9362.png)
![image](https://user-images.githubusercontent.com/91315508/224203361-da75794c-1909-4cd8-aa58-f2d4fe145aed.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/WebhookPushRequest.java line 136,180,182,360

### Describe the solution you'd like

a. Remove invalid code.
b. Use Objects.requireNonNull() to avoid NPE.
![image](https://user-images.githubusercontent.com/91315508/224203410-2cf1ea8b-8501-4452-8ca9-16b4fb2fa742.png)

c. Replace "Collections.EMPTY_LIST" by "Collections.emptyList()".
![image](https://user-images.githubusercontent.com/91315508/224203445-fed1ca2b-f0d0-4b32-b326-21736fe2bceb.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by himansh295** [comment]
Hi @Alonexc 
Is this issue still open?
