### ISSUE TITLE
[Enhancement] "getExtension()" can return null.[Trace]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3402]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224203562-e9766013-00c4-4693-ab38-0cab71692e21.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/trace/Trace.java line 123,143

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/224203579-a32dc1f2-c733-451a-9b2f-7c601ddcd136.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yangsl960702** [comment]
请问该问题已经有人解决了吗，如果没有，我可以做尝试吗

**Comment by Pil0tXia** [comment]
Closed due to the review comments at https://github.com/apache/eventmesh/pull/3632#pullrequestreview-1434053124.
