### ISSUE TITLE
[Enhancement] Make this anonymous inner class a lambda[SendSyncMessageProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3407]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224204041-afa4fd1d-8d1b-4fa7-8850-dc4f5c56a727.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java line 260
analysis and explanation:
Before Java 8, the only way to partially support closures in Java was by using anonymous inner classes. But the syntax of anonymous classes may seem unwieldy and unclear.
With Java 8, most uses of anonymous inner classes should be replaced by lambdas to highly increase the readability of the source code.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/224204081-0568b071-0b21-4b7a-a600-aee4b4048478.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Sunstreaker** [comment]
Yes I am willing to submit a PR!

**Comment by Alonexc** [comment]
@Sunstreaker Welcome to your pr.
