### ISSUE TITLE
[Enhancement] Do some code optimization[SendAsyncRemoteEventProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3408]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224204134-96f717d4-ed58-4468-a056-329c8ca17f2a.png)
![image](https://user-images.githubusercontent.com/91315508/224204139-d355bf9b-8f8c-4bef-bbc6-2de18c8e70fb.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java line 246,336

### Describe the solution you'd like

a. use Objects.requireNonNull().
![image](https://user-images.githubusercontent.com/91315508/224204175-a9c06246-2e5d-4eba-9877-7be8c19420f2.png)

b. Excessive lambda usage.
![image](https://user-images.githubusercontent.com/91315508/224204206-0d1e8b24-4b55-42c0-a0f0-454e2ad43b0e.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pandaapo** [comment]
The `event.getData().toBytes()` seems no need to be added `Objects.requireNonNull()`. It has been validated before.
