### ISSUE TITLE
[Enhancement] "getData()" can return null.[SendAsyncEventProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3410]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224204380-f154c867-d360-4daf-8282-e6c4f3d619a2.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java line 215

### Describe the solution you'd like

use Objects.requireNonNull().

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Orcohen33** [comment]
I would like to contribute to this issue.
