### ISSUE TITLE
[Enhancement] Do some code optimization[ReplyMessageProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3411]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224204460-e92e3832-66ef-42b4-b8dd-1cffec8e4094.png)
![image](https://user-images.githubusercontent.com/91315508/224204472-09aa3061-0fc1-4db3-a198-848cf52b02c7.png)
![image](https://user-images.githubusercontent.com/91315508/228766399-0cc780b7-dd06-47b1-9bca-c0043aa6be27.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ReplyMessageProcessor.java line 63,65,67,69,81,202

### Describe the solution you'd like

a. change to 'private static final'.
![image](https://user-images.githubusercontent.com/91315508/224204518-d93292d3-db5a-4b8f-8696-32ac865af12c.png)

b. Remove invalid code.
c.Invoke method(s) only conditionally.
![image](https://user-images.githubusercontent.com/91315508/228766212-9d555e61-39c7-4c67-92ec-31690bc73c98.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
This issue is open for contibution.

**Comment by cnzakii** [comment]
@Pil0tXia 

This issue has been resolved, so you should be able to close this issue.

![2024-05-04_13 39 20](https://github.com/apache/eventmesh/assets/91261012/2284d406-7dd5-4854-a700-250963ddae8e)

**Comment by Pil0tXia** [comment]
@cnzakii The task b & c haven't been accomplished yet.

![image](https://github.com/apache/eventmesh/assets/41445332/598ef496-0fa3-44ac-8b7d-1162d9d3af2b)

**Comment by cnzakii** [comment]
> The task b & c haven't been accomplished yet.

Well, I think I can do the rest.

**Comment by Pil0tXia** [comment]
@cnzakii 👍
