### ISSUE TITLE
[Enhancement] update eventmesh docs for using eventmesh storage

### ISSUE THREAD

**Issue by xwm1992** [apache/eventmesh#3422]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

change using eventmesh-storage not eventmesh-connector to describe the feature in related docs.

### Describe the solution you'd like

change using eventmesh-storage not eventmesh-connector to describe the feature in related docs.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mxsm** [comment]
@xwm1992  I will submit a pr to do this

**Comment by Pil0tXia** [comment]
Completed. Subsequent work: https://github.com/apache/eventmesh-site/issues/171
