### ISSUE TITLE
[Enhancement] Do some code optimization[EventMeshUtil]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/225789309-43c390cd-418f-4f96-9209-8b2963f976ad.png)
![image](https://user-images.githubusercontent.com/91315508/225789315-3c5fb9d9-2aba-4da3-a3b1-59ab647651f7.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java line 174,187

### Describe the solution you'd like

a. use Objects.requireNonNull()
![image](https://user-images.githubusercontent.com/91315508/225789338-09016b96-5643-4bd8-8608-a3681a9215d1.png)

b. iteration can be replaced with bulk 'Collection.addAll' call
![image](https://user-images.githubusercontent.com/91315508/225789378-469819fb-e773-4370-90c9-263370608fae.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pandaapo** [comment]
The `event.getExtension(extensionKey)` has already made a null value judgment before, so Objects.requireNonNull() is no needed.

**Comment by pandaapo** [comment]
But there are other optimization to do in my pr, including `iteration can be replaced with bulk 'Collection.addAll' call`. Could you reopen this issue again?

**Comment by Alonexc** [comment]
ok！
