### ISSUE TITLE
[Enhancement] Make this method "synchronized" to match the parent class implementation.[CloudEventTCPPubClient]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3467]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/225789702-9ccbf578-98a2-4666-b1a4-f2b7c2080e8e.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPPubClient.java line 72
analysis and explanation:
When @Overrides of synchronized methods are not themselves synchronized, the result can be improper synchronization as callers rely on the thread-safety promised by the parent class.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/225789733-85610c06-5d70-46a9-88e2-30d956fca707.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pandaapo** [comment]
I have the same doubts about this issue as https://github.com/apache/eventmesh/issues/3470#issuecomment-1518007900
