### ISSUE TITLE
[Enhancement] Make this method "synchronized" to match the parent class implementation.[CloudEventTCPSubClient]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3468]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/225789763-cd14fe11-2fe9-426b-bab0-ab09bd484801.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPSubClient.java line 79
analysis and explanation:
When @Overrides of synchronized methods are not themselves synchronized, the result can be improper synchronization as callers rely on the thread-safety promised by the parent class.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/225789799-aacbe732-ed3e-4f3b-ac6b-c0df24cd7b77.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pandaapo** [comment]
I have the same doubts about this issue as https://github.com/apache/eventmesh/issues/3470#issuecomment-1518007900
