### ISSUE TITLE
[Enhancement] Make this method "synchronized" to match the parent class implementation.[EventMeshMessageTCPPubClient]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3469]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/225789839-0795c2f2-0a40-4904-abc9-413b2e232c00.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPPubClient.java line 68
analysis and explanation:
When @Overrides of synchronized methods are not themselves synchronized, the result can be improper synchronization as callers rely on the thread-safety promised by the parent class.

### Describe the solution you'd like

add "synchronized" to the method.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pandaapo** [comment]
I have the same doubts about this issue as #3470.
