### ISSUE TITLE
[Enhancement] Do some code optimization[HttpProtocolAdaptor]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3472]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/225790049-ecc5c23f-9cb3-40be-8871-8d4ce3e6b735.png)
![image](https://user-images.githubusercontent.com/91315508/225790059-a783ed3e-7286-4e03-a60c-5471b0f12b66.png)
![image](https://user-images.githubusercontent.com/91315508/229456398-7e2d5132-25d2-48a3-94ff-323cc8c23a25.png)

located at:
eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/HttpProtocolAdaptor.java line 81,102
eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/resolver/HttpRequestProtocolResolver.java line 95

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/225790085-6017a9c0-4d16-446c-a2b7-14b814eaac51.png)
![image](https://user-images.githubusercontent.com/91315508/225790098-076454e7-fe3e-4929-8ec4-f35621d5664d.png)
![image](https://user-images.githubusercontent.com/91315508/229456479-964ca41f-f3cd-4bd5-9acf-5624acb466a1.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Alonexc** [comment]
@Sunstreaker OK! You can submit a pr first.

**Comment by harshithasudhakar** [comment]
@Sunstreaker Are you still working on this? I would like to work on it, if not.

**Comment by Alonexc** [comment]
@Sunstreaker  If there is no pr for more than two weeks, other contributors are welcome to contribute.
