### ISSUE TITLE
[Enhancement] Optimize the eventmesh-admin of EventMesh

### ISSUE THREAD

**Issue by xwm1992** [apache/eventmesh#3495]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

At present, eventmesh-admin provides a management interface for eventmesh storage, but it only implements the management function of rocketmq, which needs to be further expanded. At the same time, it can provide CLI for users to quickly start and experience. 

### Describe the solution you'd like

At present, eventmesh-admin provides a management interface for eventmesh storage, but it only implements the management function of rocketmq, which needs to be further expanded. At the same time, it can provide CLI for users to quickly start and experience. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by fabian4** [comment]
Hi @xwm1992, I think I can keep going on with this one since I have just done the redis-connector part. 

Also data encoding and decoding in redis-connector are still need improvement, so I can start with redis-storage-admin first at the same time.

Plz assign to me.

**Comment by Pil0tXia** [comment]
@fabian4 Welcome, please add new changes to `eventmesh-admin-redis` module.

**Comment by Pil0tXia** [comment]
Closing as `eventmesh-admin` has been migrated to the eventmesh-dashboard repository.
