### ISSUE TITLE
[Enhancement] Some optimization of the code.[SubscribeTask]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3502]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/226833270-0dc6fbc7-806d-4a5c-af36-363e75db685b.png)
located at:
eventmesh-storage/eventmesh-storage-pravega/src/main/java/org/apache/eventmesh/storage/pravega/client/SubscribeTask.java line 50
analysis and explanation:
a. common part can be extracted removing branch
b. reduce the total number of continue statements in this loop to use at most one.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/226833327-6b6bfe23-a434-4b73-a1d5-8982b121f2e9.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by harshithasudhakar** [comment]
I'd like to work on this.

**Comment by Alonexc** [comment]
You are very welcome to pr.
