### ISSUE TITLE
[Enhancement] Swap these 2 arguments so they are in the correct order: expected value, actual value.[ConfigurationHolderTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3511]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/226835498-58ae8cfb-6064-404f-bca9-510be23c62d3.png)
located at:
eventmesh-storage/eventmesh-storage-rabbitmq/src/test/java/org/apache/eventmesh/storage/rabbitmq/config/ConfigurationHolderTest.java line 50-60
analysis and explanation:
The standard assertions library methods such as org.junit.Assert.assertEquals, and org.junit.Assert.assertSame expect the first argument to be the expected value and the second argument to be the actual value. For AssertJ, it’s the other way around, the argument of org.assertj.core.api.Assertions.assertThat is the actual value, and the subsequent calls contain the expected values. Swap them, and your test will still have the same outcome (succeed/fail when it should) but the error messages will be confusing.

### Describe the solution you'd like

Swap actual and expected values.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sumitdethe27** [comment]
Hey @Alonexc 
is this issue available, i would like to work on it.

**Comment by sumitdethe27** [comment]
Hey is this issue available, I would like to work on it.

**Comment by Alonexc** [comment]
@sumitdethe27 This issue is not yet fixed, your pr is welcome.

**Comment by sumitdethe27** [comment]
Sorry for the delay @Alonexc , I am working on this, and  provide a pr asap

**Comment by Alonexc** [comment]
It's okay, your contributions are welcome.
