### ISSUE TITLE
[Enhancement] Swap these 2 arguments so they are in the correct order: expected value, actual value.[PravegaStorageConfigTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3513]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/226836070-21d3bc1c-202d-48f5-9d0f-afad7f1d9afe.png)
located at:
eventmesh-storage/eventmesh-storage-pravega/src/test/java/org/apache/eventmesh/storage/pravega/config/PravegaStorageConfigTest.java line 50,51,53,54,56-58
analysis and explanation:
The standard assertions library methods such as org.junit.Assert.assertEquals, and org.junit.Assert.assertSame expect the first argument to be the expected value and the second argument to be the actual value. For AssertJ, it’s the other way around, the argument of org.assertj.core.api.Assertions.assertThat is the actual value, and the subsequent calls contain the expected values. Swap them, and your test will still have the same outcome (succeed/fail when it should) but the error messages will be confusing.

### Describe the solution you'd like

Swap actual and expected values.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by akashsawan1** [comment]
I would like to work on this.

/assign

**Comment by Alonexc** [comment]
@akashsawan1 Welcome, you can submit a pr first.

**Comment by akashsawan1** [comment]
I have already submitted a PR 2 days back.
Please check and let me know if any change is required.

https://github.com/apache/eventmesh/pull/3658
