### ISSUE TITLE
[Enhancement] Swap these 2 arguments so they are in the correct order: expected value, actual value.[EventMeshTCPConfigurationTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3519]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/226837832-39e7b818-603c-45e0-bd52-f209eba6323b.png)
Located at:
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfigurationTest.java line 44-68
analysis and explanation:
The standard assertions library methods such as org.junit.Assert.assertEquals, and org.junit.Assert.assertSame expect the first argument to be the expected value and the second argument to be the actual value. For AssertJ, it’s the other way around, the argument of org.assertj.core.api.Assertions.assertThat is the actual value, and the subsequent calls contain the expected values. Swap them, and your test will still have the same outcome (succeed/fail when it should) but the error messages will be confusing.

### Describe the solution you'd like

Swap actual and expected values.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by harshithasudhakar** [comment]
I would like to work on this. Please assign it to me.

**Comment by Alonexc** [comment]
Welcome to the eventmesh community, you can start by submitting a pr.

**Comment by harshithasudhakar** [comment]
I really appreciate the welcome! Looking forward to contribute to the community!! Sure, I shall work on it.

**Comment by TheAPratap** [comment]
\assign

**Comment by harshithasudhakar** [comment]
I would like to know if there any slack community channels or mailing lists I'd join, to get in touch with the community?

**Comment by xwm1992** [comment]
> I would like to know if there any slack community channels or mailing lists I'd join, to get in touch with the community?

The community contact information is under the code page, both wechat and slack.

**Comment by harshithasudhakar** [comment]
> > I would like to know if there any slack community channels or mailing lists I'd join, to get in touch with the community?
> 
> The community contact information is under the code page, both wechat and slack.

Thank you for the info, but WeChat is not available in my country and the slack link doesn't seem to exist.

**Comment by Alonexc** [comment]
Yes, the current link is not available and will be updated later.
