### ISSUE TITLE
[Enhancement] Swap these 2 arguments so they are in the correct order: expected value, actual value.[EventMeshHTTPConfigurationTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3521]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/226838049-21a58313-1abc-4221-b9f0-d8401c309dbf.png)
![image](https://user-images.githubusercontent.com/91315508/226838074-2b21b442-6d68-4bc2-a3b6-0a3b46110de0.png)
![image](https://user-images.githubusercontent.com/91315508/226838094-96e6cdee-8cd4-4574-a307-4a35eae7ffcb.png)
Located at:
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfigurationTest.java line 48-72,77,81
analysis and explanation:
The standard assertions library methods such as org.junit.Assert.assertEquals, and org.junit.Assert.assertSame expect the first argument to be the expected value and the second argument to be the actual value. For AssertJ, it’s the other way around, the argument of org.assertj.core.api.Assertions.assertThat is the actual value, and the subsequent calls contain the expected values. Swap them, and your test will still have the same outcome (succeed/fail when it should) but the error messages will be confusing.

### Describe the solution you'd like

Swap actual and expected values.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by monish-byte** [comment]
hey @Alonexc i am beginner to open source contribution. i would like to work on this issue with your guidance. thank you

**Comment by Alonexc** [comment]
@monish-byte Hello, welcome to the eventmesh community, this issue has been submitted pr, there are other similar issues, see if you are interested, your contribution is very welcome.
