### ISSUE TITLE
[Bug] kafka cloudevent serialization issue

### ISSUE THREAD

**Issue by sq-yang-1** [apache/eventmesh#3528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

Other

### What happened

kafka cloudevent serialization issue

### How to reproduce

use connector-kafka plugin send message;

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mxsm** [comment]
@sq-yang-1 Thanks for your contribution first, This module has been migrated to the corresponding module in the store.At the same time, the current code is correct and does not need to be modified. For specific usage examples, please refer to the CloudEvents official website.
https://cloudevents.github.io/sdk-java/kafka.html
