### ISSUE TITLE
[Enhancement] Method invocation may produce 'NullPointerException'.[CloudEventsProtocolAdaptor]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3649]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/230524865-97bbd239-1897-4eb7-8be6-722b68080bcf.png)
located at:
eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/CloudEventsProtocolAdaptor.java line 121,130

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/230524893-79040c74-5db1-43cc-a024-dc4d2cc1fdbe.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dipankr** [comment]
Hi, 
I had done the code changes for this earlier today but got caught up with other issues, you can delete my PR since there is already another one.
