### ISSUE TITLE
[Enhancement] Code reuse is extracted as a method.[SendMessageBatchV2ProtocolResolver]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3652]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/230524997-98f3498f-5530-4543-a2fb-3480f0980940.png)
located at:
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/http/SendMessageBatchV2ProtocolResolver.java line 67-91,94-118

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/230525025-3e08e66f-9896-4d2f-acc6-e12c6721b991.png)
![image](https://user-images.githubusercontent.com/91315508/230525033-5dc8fb56-7b1a-4916-b85f-1af4bcc5be5e.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dipankr** [comment]
Hi,
I have done the code changes and created a PR, please review.
thanks

**Comment by dipankr** [comment]
also if you can delete the other pr (closed), there were code changes from another pr as this branch was created from another branch instead of master.
