### ISSUE TITLE
[Enhancement] Code reuse is extracted as a method.[SendMessageRequestProtocolResolver]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3653]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/230525066-07351a8e-d3c3-4480-8107-a65727b361b6.png)
located at:
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/http/SendMessageRequestProtocolResolver.java line 67-98,101-132

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/230525082-94a85584-6a13-44d1-af9d-dfcfa640cda6.png)
![image](https://user-images.githubusercontent.com/91315508/230525092-49525a5c-83c0-4a00-8d76-85469fb7e9c8.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by monish-byte** [comment]
hey @Alonexc I would like to like to work on this. Can you please explain more about the issue?

**Comment by Alonexc** [comment]
@monish-byte Of course, you are very welcome to pr.
