### ISSUE TITLE
[Bug] The slack link being used everywhere is outdated, doesn't work

### ISSUE THREAD

**Issue by dipankr** [apache/eventmesh#3702]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

The slack link is not valid anymore, if anyone can share the updated invite link I can update it

### How to reproduce

click on the slack invite link from anywhere within the repo

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
@dipankr https://join.slack.com/t/apacheeventmesh/shared_invite/zt-1t1816dli-I0t3OE~IpdYWrZbIWhMbXg 
I will update it where used it.

**Comment by dipankr** [comment]
> @dipankr https://join.slack.com/t/apacheeventmesh/shared_invite/zt-1t1816dli-I0t3OE~IpdYWrZbIWhMbXg 
> I will update it where used it.

If this is done, we can close this issue

**Comment by harshithasudhakar** [comment]
Hi all! As someone who is new to contributing to open-source projects, I would greatly appreciate if someone would guide me through on the process of setting up and conducting tests using EventMesh on Windows.

**Comment by dipankr** [comment]
> Hi all! As someone who is new to contributing to open-source projects, I would greatly appreciate if someone would guide me through on the process of setting up and conducting tests using EventMesh on Windows.

for setting up you can go through readme of the project and follow the steps. if you face any build issues (I did), you can try using a VPN while running the build. Any other issue, you can reach out to me, I can try to help.

**Comment by harshithasudhakar** [comment]
> > Hi all! As someone who is new to contributing to open-source projects, I would greatly appreciate if someone would guide me through on the process of setting up and conducting tests using EventMesh on Windows.
> 
> for setting up you can go through readme of the project and follow the steps. if you face any build issues (I did), you can try using a VPN while running the build. Any other issue, you can reach out to me, I can try to help.

Oh, thank you! I'll get back to you when I face any issues.
