### ISSUE TITLE
[Enhancement] Do some code optimization[JaegerTraceService]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3721]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/231701785-3a78148d-076b-4e2b-9e20-3244a308a352.png)
located at:
eventmesh-trace-plugin/eventmesh-trace-jaeger/src/main/java/org/apache/eventmesh/trace/jaeger/JaegerTraceService.java line 126,127,132,133
analysis and explanation:
a. Not annotated parameter overrides @ParametersAreNonnullByDefault parameter
b. A "NullPointerException" could be thrown; "carrier" is nullable here.

### Describe the solution you'd like

add `@Nullable` and use Objects.repuireNonNull().
![image](https://user-images.githubusercontent.com/91315508/231701876-ac1a8c9e-6c8a-445c-8039-137503a6aefc.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pandaapo** [comment]
I will use `@Nonnull` instead of `@Nullable` + `Objects.requireNonNull()` as what I did before.

**Comment by Alonexc** [comment]
It's good.
