### ISSUE TITLE
[Enhancement] Not annotated parameter overrides @ParametersAreNonnullByDefault parameter[PravegaCloudEventWriter]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3725]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/231702913-fdc6559b-7384-477a-ae79-0af8ae108612.png)
![image](https://user-images.githubusercontent.com/91315508/231702935-7487404f-c390-4e5b-af45-aac7b767dee1.png)
located at:
eventmesh-storage-plugin/eventmesh-storage-pravega/src/main/java/org/apache/eventmesh/storage/pravega/client/PravegaCloudEventWriter.java line 42,60

### Describe the solution you'd like

add `@Nonnull`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pandaapo** [comment]
In the method `setEvent(EventFormat, byte[])`, the first param is unused. Can I only add `@Nonnull` to the second param?

**Comment by Alonexc** [comment]
Yes, all need to be added.
