### ISSUE TITLE
[Enhancement] Redundant import and `return` statements.

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3762]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

This issue is a subproject issue of eventmesh. the subproject address is:
https://github.com/apache/eventmesh-workflow
![image](https://user-images.githubusercontent.com/91315508/233279678-baf10b8d-febc-4e71-be43-cf7f4ebce34c.png)
![image](https://user-images.githubusercontent.com/91315508/233279703-ae6a86a6-e7b1-4a74-9a46-132ff020d2a1.png)
located at:
eventmesh-workflow/cmd/engine/main.go line 33,34
eventmesh-workflow/cmd/controller/workflow.go line 123

### Describe the solution you'd like

remove the redundant `return` and import.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nayaldivya** [comment]
Hi! Can i take this up?

**Comment by Pil0tXia** [comment]
@nayaldivya Hi, how is the progress?

**Comment by kashvi0** [comment]
hi! can i fix do this, please?

**Comment by Pil0tXia** [comment]
@kashvi0 Welcome!

**Comment by kashvi0** [comment]
hi! i just noticed that the issue had already been fixed. i should've checked this before asking. i apologize for any inconvenience caused.
