### ISSUE TITLE
[Enhancement] should use time.Since instead of time.Now().Sub[consumer_manager.go]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3766]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

This issue is a subproject issue of eventmesh. the subproject address is:
https://github.com/apache/eventmesh-go
![image](https://user-images.githubusercontent.com/91315508/233281752-159509e1-3dd5-495c-af2a-6720f3dde3ab.png)
located at:
eventmesh-go/runtime/core/protocol/grpc/consumer/consumer_manager.go line 174

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/233281978-665daf93-e284-4270-92f7-197d7b9d44f7.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by harshithasudhakar** [comment]
The PR that addresses the issue hasn't been merged yet.
https://github.com/apache/eventmesh-go/pull/9

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh-go/pull/9
