### ISSUE TITLE
[Enhancement] should use time.Since instead of time.Now().Sub[producer_processor.go]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3768]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

This issue is a subproject issue of eventmesh. the subproject address is:
https://github.com/apache/eventmesh-go
![image](https://user-images.githubusercontent.com/91315508/233282459-edd048bd-e581-4562-b1e5-4151f346afc5.png)
located at:
eventmesh-go/runtime/core/protocol/grpc/producer/producer_processor.go line 102,107,165,170,223,235,292,296

### Describe the solution you'd like

use time.Since instead of time.Now().Sub

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by harshithasudhakar** [comment]
The link to the PR that addresses this issue.
https://github.com/apache/eventmesh-go/pull/10
