### ISSUE TITLE
[Enhancement] Remove invalid code.[consumer_test.go]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3773]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

This issue is a subproject issue of eventmesh. the subproject address is:

https://github.com/apache/eventmesh-go

![image](https://user-images.githubusercontent.com/91315508/233284603-55aca924-6999-49aa-b8d7-da3a013eb35e.png)
located at:
eventmesh-go/plugin/connector/rocketmq/consumer_test.go line 96-119

### Describe the solution you'd like

Remove.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by harshithasudhakar** [comment]
The issue has been resolved.
