### ISSUE TITLE
[Enhancement] Remove invalid code.[producer_test.go]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3774]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

This issue is a subproject issue of eventmesh. the subproject address is:

https://github.com/apache/eventmesh-go

![image](https://user-images.githubusercontent.com/91315508/233284780-ed477899-6550-48ad-9d00-0b51176d6561.png)
located at:
eventmesh-go/plugin/connector/rocketmq/producer_test.go line 190-214

### Describe the solution you'd like

Remove.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by harshithasudhakar** [comment]
@Alonexc This issue seems to be resolved. 
https://github.com/apache/eventmesh-go/commit/19fb439312cb931336f11d69e5e739398d6bc7d0

**Comment by luahan77m** [comment]
Hi, I'm new to open source and want to try to solve some simple problems. Can you assign this issue to me? I would appreciate it!

**Comment by harshithasudhakar** [comment]
Welcome to EventMesh @luahan77m !
Please pick another issue from the `good first issue` label, as this issue seems to be resolved. I shall close this issue.
