### ISSUE TITLE
[Question] Is there an official guide to configure and run eventmesh in Docker?

### ISSUE THREAD

**Issue by HattoriHenzo** [apache/eventmesh#3808]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

Hello,

I tried to configure _eventmesh_ and run it in Docker but I had some issues. I also follow this updated [post](https://github.com/apache/eventmesh/issues/3587), but still have issues. 
Can you please provide a procedure to do this configuration on Windows and Linux.

Also, does a specific port is used to do a remote debug on the _eventmesh_ Docker image?

**Comment by mxsm** [comment]
@HattoriHenzo  The current official website only supports up to version 1.4, and there are no corresponding documents or Docker images for the latest version at the moment. We will update them later. If you want to use it, you can write a Dockerfile and package it with the latest code for deployment. You can refer to the ISSUE #3587 for more details.

**Comment by HattoriHenzo** [comment]
@mxsm Thanks for your reply. I already tried this guideline but I have an issue with Docker. I gave more details about my issue here: https://github.com/apache/eventmesh/issues/3587#issuecomment-1518345251. Any help will be very appreciated.

**Comment by mxsm** [comment]
@HattoriHenzo  run this command first
```
./gradlew clean jar dist -x test -x checkstyleMain -x javaDoc && ./gradlew installPlugin && ./gradlew tar
```
then put dockerfile to build dirctory that has .tar.gz file

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh-site/pull/170 and you may see guides at https://eventmesh.apache.org/docs/instruction/runtime-with-docker
