### ISSUE TITLE
[Enhancement] Do some code optimization.[MessageEntity]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3824]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/234746406-46292c37-892c-45e5-929a-801e26bc1b1b.png)
located at:
eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/broker/model/MessageEntity.java
analysis and explanation:
a. 'MessageEntity' does not define a 'serialVersionUID' field
b. Make "message" transient or serializable.

### Describe the solution you'd like

a. add serialVersionUID
b. add transient
![image](https://user-images.githubusercontent.com/91315508/234746482-44550277-36c6-4a5c-a636-88791acfc900.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by j1803248734** [comment]
Can I work on this issue? kindly assign it to me!
