### ISSUE TITLE
[Enhancement] Do some code optimization.[TopicMetadata]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3825]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/234746520-b20773ef-4187-46d3-948a-9e0e3d25bc0a.png)
located at:
eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/broker/model/TopicMetadata.java

### Describe the solution you'd like

a. add serialVersionUID
b. add final
![image](https://user-images.githubusercontent.com/91315508/234746594-7f474564-97cc-4635-96f1-9f59740c312f.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tooo-bad** [comment]
Does this problem still need to be solved? I want to contribute to it.

**Comment by Pil0tXia** [comment]
@tooo-bad Welcome to EventMesh community. It's OK for this issue to submit a PR.

**Comment by tooo-bad** [comment]
I have submitted a PR, please review it. This is my first time submitting a PR and I may not have done well. If I make an error, please correct it. Thank you.
If I solve this problem correctly, I will solve the other issues I left a message about.
