### ISSUE TITLE
[Enhancement] Do some code optimization.[StandaloneAdminTest TestUtils]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3828]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/234746965-08e09d00-818b-4517-81e9-c708fd0b186a.png)
![image](https://user-images.githubusercontent.com/91315508/234746978-bc1bd8f2-98fe-484f-8843-a26ac84f5773.png)
![image](https://user-images.githubusercontent.com/91315508/234746986-e7373351-6019-4fea-9be2-50644d9a55ce.png)
![image](https://user-images.githubusercontent.com/91315508/234746997-a230fff8-ea30-4280-8262-85ae974c7755.png)
located at:
eventmesh-storage-plugin/eventmesh-storage-standalone/src/test/java/org/apache/eventmesh/storage/standalone/admin/StandaloneAdminTest.java line 73,90,99
eventmesh-storage-plugin/eventmesh-storage-standalone/src/test/java/org/apache/eventmesh/storage/standalone/TestUtils.java line 66
analysis and explanation:
a. This method makes two consecutive calls to the same method, using the same constant parameters, on the same instance, without any intervening changes to the objects. If this method does not make changes to the object, which it appears it doesn't, then making two calls is just a waste. These method calls could be combined by assigning the result into a temporary variable, and using the variable the second time.
b. Method needlessly boxes a boolean constant.
c. Method builds a list from one element using Arrays.asList This method builds a list using Arrays.asList(foo), passing in a single element. Arrays.asList needs to first create an array from this one element, and then build a List that wraps this array. It is simpler to use Collections.singletonList(foo), which does not create the array, and produces a far simpler instance of List. Since both of these arrays are immutable (from the List's point of view) they are equivalent from a usage s tandpoint.

### Describe the solution you'd like

a. Use intermediate variables as storage.
![image](https://user-images.githubusercontent.com/91315508/234747056-e77b4a94-89aa-48db-a15c-0095682ac00e.png)

b. Use 'Boolean.xxxx'.
![image](https://user-images.githubusercontent.com/91315508/234747082-1bd634e3-3232-4d0c-b744-14a2f7b0eac8.png)

c. Replace with Collections.singletonList().
![image](https://user-images.githubusercontent.com/91315508/234747104-4adc770c-42cc-4883-8471-05b67f738c79.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dr-divago** [comment]
Hi @Alonexc , can I work on the issue?
