### ISSUE TITLE
[Enhancement] InterruptedExceptions should not be ignored in the code.[ProducerImpl]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3830]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/234747254-aa8ee4bd-55c7-4cee-8b4c-4d9619e75bdb.png)
![image](https://user-images.githubusercontent.com/91315508/234747273-b548da1d-3cfe-4e42-86d5-96415238b5e7.png)
located at:
eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/producer/ProducerImpl.java line 85,99,113,140,
analysis and explanation:
InterruptedExceptions should never be ignored in the code, and simply logging the exception counts in this case as "ignoring". The throwing of the InterruptedException clears the interrupted state of the Thread, so if the exception is not handled properly the information that the thread was interrupted will be lost. Instead, InterruptedExceptions should either be rethrown - immediately or after cleaning up the method’s state - or the thread should be re-interrupted by calling Thread.interrupt() even if this is supposed to be a single-threaded application. Any other course of action risks delaying thread shutdown and loses the information that the thread was interrupted - probably without finishing its task.
Similarly, the ThreadDeath exception should also be propagated. According to its JavaDoc:
If ThreadDeath is caught by a method, it is important that it be rethrown so that the thread actually dies.

### Describe the solution you'd like

Just for reference, if you have better modifications, please correct me:
![image](https://user-images.githubusercontent.com/91315508/234747324-4406c296-9d3b-4499-92fd-2527089533e7.png)

Remove this useless assignment; "msg" already holds the assigned value along all execution paths.
![image](https://user-images.githubusercontent.com/91315508/234747352-bb8d733c-5222-4d81-bd57-a79ab02fb7a1.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pandaapo** [comment]
About removing `supplySysProp(msg, cloudEvent)`, I have a different opinion. In method `supplySysProp(msg, cloudEvent)`, the `Message` object seems to be set more value than before calling `supplySysProp(msg, cloudEvent)`. I'm not sure the reason of deleting it.

**Comment by Alonexc** [comment]
![image](https://user-images.githubusercontent.com/91315508/236083176-f20dc606-e422-4327-bded-fce707a60970.png)
Instead of removing `supplySysProp(msg, cloudEvent)`, we remove the intermediate quantity `msg`. The method itself returns the value of this allocation.
![image](https://user-images.githubusercontent.com/91315508/236083424-17af2439-37ca-4fa8-8d94-46881be9adcb.png)

**Comment by pandaapo** [comment]
Ooops. I misunderstood your meaning. Thanks.

**Comment by j1803248734** [comment]
Can I work on this issue? kindly assign it to me!

**Comment by Pil0tXia** [comment]
@j1803248734 You are welcome to submit a PR.

**Comment by jevinjiang** [comment]
Completed, pull request submitted, please review.

**Comment by jevinjiang** [comment]
I observed that the sendOneway, sendAsync, and reply methods did not return the sendResult object. Why does the send method need to return it?

**Comment by pandaapo** [comment]
> I observed that the sendOneway, sendAsync, and reply methods did not return the sendResult object. Why does the send method need to return it?

@jevinjiang 
Neither `sendOneway` nor `sendAsync` need to be concerned with the returned response, unlike the `send` method.

`sendOneway`和`sendAsync`都不需要关注返回的响应，和`send`方法不同。
