### ISSUE TITLE
[Enhancement] Do some code optimization.[ZookeeperMetaService]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3833]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/234748059-f7f2782e-acb6-4dd4-b0e2-b75b320550bf.png)
![image](https://user-images.githubusercontent.com/91315508/234748070-4d456d98-8277-45c8-a9ff-e46bc66bcbaf.png)
located at:
eventmesh-registry-plugin/eventmesh-registry-zookeeper/src/main/java/org/apache/eventmesh/registry/zookeeper/service/ZookeeperRegistryService.java line 71,202-223,251-272.

### Describe the solution you'd like

a. Change to `private` modifier.
b. Repeat code extraction as method.
![image](https://user-images.githubusercontent.com/91315508/234748118-16c6c0f8-5a2a-4060-ba9a-30afba792cd7.png)
![image](https://user-images.githubusercontent.com/91315508/234748124-8bca792a-d2e6-4563-8142-c8bd42f620de.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Ish1yu** [comment]
Hello, I am a beginner in eventmesh. Upon seeing the problem described in this issue, I wonder if eventmesh has already been refactored. I couldn't find the location of eventmesh-registry-zookeeper, but I found one located in eventmesh metaeventmesh-meta\eventmesh-meta-zookeeper\src\main\java\org\apache\eventmesh\meta\zookeeper\service\ZookeeperMetaService. Do I need to modify it here?

Meanwhile, regarding the document "Quick Start", I think the description of meta (Registry Meta Service) is too simple. I only understood it based on the code. Can I try to improve the Chinese description of Quick Start in the document?（https://eventmesh.apache.org/zh/docs/instruction/runtime）

**Comment by Alonexc** [comment]
Yes, the location may have changed due to updates to the code module, this looks unfinished, welcome to the eventmesh community.
