### ISSUE TITLE
[Enhancement] Repeat the operation using method instead.

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3834]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/234748222-0458dd1a-980e-4338-9788-33d208616746.png)
located at:
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/grpc/GrpcMessageProtocolResolver.java line 225-244

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/234748259-3984dc74-e0f6-4e8d-8eb0-dedddf9fdee6.png)
![image](https://user-images.githubusercontent.com/91315508/234748274-6e87c106-b729-4d12-a27e-846e07db72d3.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scwlkq** [comment]
@Pil0tXia The class this issue mentiond has be deprecated.

**Comment by Pil0tXia** [comment]
Ternary operations existed in EventMesh are few now and there's no need for an addtional utility method.
