### ISSUE TITLE
[Enhancement] Replace some logic with existing APIs. Merge some logic.

### ISSUE THREAD

**Issue by pandaapo** [apache/eventmesh#3852]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

**org.apache.eventmesh.protocol.cloudevents.resolver.tcp.TcpMessageProtocolResolver:**

Some logic have been implemented by existing APIs, so no need to implement them again.

Some if branches in`buildEvent(Header header, String cloudEventJson)` can be merged.

**org.apache.eventmesh.protocol.meshmessage.resolver.tcpTcp.MessageProtocolResolver:**

`cloudEventBuilder = cloudEventBuilder.withExtension().withExtension()...`, this assignment is unecessary.

Entry is more efficient than keySet + get(key).

### Describe the solution you'd like

**org.apache.eventmesh.protocol.cloudevents.resolver.tcp.TcpMessageProtocolResolver:**

Use existing APIs.

Merge if braches.

**org.apache.eventmesh.protocol.meshmessage.resolver.tcpTcp.MessageProtocolResolver:**

Use var of reference type correctly.

Use Entry to access Map.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yelbom** [comment]
> ### Search before asking
> 
> 
> 
> - [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.
> 
> 
> 
> 
> 
> ### Enhancement Request
> 
> 
> 
> org.apache.eventmesh.protocol.cloudevents.resolver.tcp.TcpMessageProtocolResolver:
> 
> 
> 
> Some logic have been implemented by existing APIs, so no need to implement them again.
> 
> 
> 
> The if branches can be merged.
> 
> 
> 
> ### Describe the solution you'd like
> 
> 
> 
> org.apache.eventmesh.protocol.cloudevents.resolver.tcp.TcpMessageProtocolResolver:
> 
> 
> 
> Use existing APIs.
> 
> 
> 
> Merge if braches.
> 
> 
> 
> ### Are you willing to submit PR?
> 
> 
> 
> - [X] **Yes** I am willing to submit a PR!

**Comment by pandaapo** [comment]
The community welcomes discussions, questions, contributions, and other technical related content, but please do not post such comments that have no meaning. @yelbom
