### ISSUE TITLE
[Enhancement] Nullcheck of value previously dereferenced

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3900]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/d66c9b65-39f4-4a8e-89df-3bf4e0afb916)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/Operation.java line 87-89
analysis and explanation:
A value is checked here to see whether it is null, but this value can't be null because it was previously dereferenced and if it were null a null pointer exception would have occurred at the earlier dereference. Essentially, this code and the previous dereference disagree as to whether this value is allowed to be null. Either the check is redundant or the previous dereference is erroneous.

### Describe the solution you'd like

Remove redundant NPE checks.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Ishaan29** [comment]
Hi @Alonexc 

I am interested in solving this issue. 

looks Like both the `Objects.requreNonNull ` and the latter check `extensionRegistry == null` are checking the same check and throwing a uncaught NPE. 

could I raise a PR with removal of additional `null` check ?

**Comment by Alonexc** [comment]
Welcome, have replied under your pr.
