### ISSUE TITLE
[Enhancement] Method needlessly defines parameter with concrete classes [NetUtils]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3902]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/c3b8a66b-c1a4-46b2-9f8d-1b42a488d47d)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/NetUtils.java line 74
analysis and explanation:
This method uses concrete classes for parameters when only methods defined in an implemented interface or superclass are used. Consider increasing the abstraction of the interface to make low impact changes easier to accomplish in the future.

### Describe the solution you'd like

Use `Collection` instead of `List`.
![image](https://github.com/apache/eventmesh/assets/91315508/3280b587-a6f9-4da3-8442-ce97348ee7de)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sumitdethe27** [comment]
Hey @Alonexc 
is this issue available, i would like to work on it.

**Comment by sumitdethe27** [comment]
Hey 
is this issue available, I would like to work on it.
