### ISSUE TITLE
[Enhancement] Method needlessly defines parameter with concrete classes[EventMeshUtil]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3906]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/51c2946d-2536-4add-9af7-72a8b71d0cb8)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java line 247
analysis and explanation:
This method uses concrete classes for parameters when only methods defined in an implemented interface or superclass are used. Consider increasing the abstraction of the interface to make low impact changes easier to accomplish in the future.

### Describe the solution you'd like

Use `Collection` instead of `List`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tooo-bad** [comment]
Does this problem still need to be solved? I want to contribute to it.

**Comment by Pil0tXia** [comment]
@tooo-bad I recommend you to submit PRs one by one to get familiar with the collaboration of community.
