### ISSUE TITLE
[Enhancement] Code optimization. [HttpRequestProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3908]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/c468658d-a580-403a-9562-71f476f962c9)
![image](https://github.com/apache/eventmesh/assets/91315508/be323070-bcbc-4745-958b-741f0711f16a)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/HttpRequestProcessor.java line 46,56
analysis and explanation:
This method prints a stack trace to the console. This is non configurable, and causes an application to look unprofessional. Switch to using loggers so that users can control what is logged and where.

### Describe the solution you'd like

![image](https://github.com/apache/eventmesh/assets/91315508/c132c1fc-1000-47a5-b4dd-1b5452aeb39f)
![image](https://github.com/apache/eventmesh/assets/91315508/8e1a8181-9444-4ffd-844d-b559dfef8a0b)
![image](https://github.com/apache/eventmesh/assets/91315508/e0bd0d82-7cd3-4f7a-b4e6-ebd3736b2603)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Elkiwa** [comment]
@Alonexc May I grab this issue?

**Comment by Alonexc** [comment]
@Elkiwa Welcome to the EventMesh community, it seems that someone has already submitted a pr. you can see other issues.

**Comment by Elkiwa** [comment]
I see. I‘ll try to contribute somewhere else.

**Comment by Alonexc** [comment]
You are very welcome to participate.
