### ISSUE TITLE
[Question] What is the role of OpenTelemetry in metrics plugin?

### ISSUE THREAD

**Issue by pandaapo** [apache/eventmesh#3911]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

@Roc-00 Hello. I want to know what is the role of OpenTelemetry in eventmesh-metrics-plugin? Does it unify the metrics data format, or collect the metrics data in EventMesh? Looking forward to your reply.

**Comment by Roc-00** [comment]
OpenTelemetry uniformly converts the collected metrics into OpenTelemetry's metric format in eventmesh-metrics-plugin, which can be visualized using visualization tools already supported by OpenTelemetry, such as Prometheus.

**Comment by pandaapo** [comment]
So converting is its work here, collecting data is not, right?

**Comment by Roc-00** [comment]
> @Roc-00 So converting is its work here, collecting data is not, right?

yes

**Comment by pandaapo** [comment]
@Roc-00 Thank you!
