### ISSUE TITLE
[Enhancement] GrpcSummaryMetrics and TcpSummaryMetrics can share an parent class

### ISSUE THREAD

**Issue by pandaapo** [apache/eventmesh#3917]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

We can design a parent class for GrpcSummaryMetrics and TcpSummaryMetrics as many things in them are the same with each other.

### Describe the solution you'd like

 Design a parent class for GrpcSummaryMetrics and TcpSummaryMetrics.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mxsm** [comment]
Hi @pandaapo I hava refactored this module. ISSUE #3430

**Comment by pandaapo** [comment]
> Hi @pandaapo I hava refactored this module. ISSUE #3430

Oh! I close this now. By the way, that is truly too large as a single pull request.

**Comment by pandaapo** [comment]
> > Hi @pandaapo I hava refactored this module. ISSUE #3430
> 
> Oh! I close this now. By the way, the linked pr is truly too large as a single pull request.
