### ISSUE TITLE
[Enhancement] Code optimization.[AbstractTask]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4020]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/d4fd65ec-2106-46da-8d82-0f7a518619fc)
![image](https://github.com/apache/eventmesh/assets/91315508/0bf199f8-f927-4ec6-9f1a-8b5e5d5d782a)
![image](https://github.com/apache/eventmesh/assets/91315508/cb0878a6-3a16-40c3-9afa-a6697b934ce9)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/AbstractTask.java line 30,34
analysis and explanation:
a. Synchronization on a non-final field 'session'
b. Change the visibility of this constructor to "protected".

### Describe the solution you'd like

a. add final
b. change the modifier to protected.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by luahan77m** [comment]
Hello, I 'm interested in this issue. Can I try it?

**Comment by harshithasudhakar** [comment]
> Hello, I 'm interested in this issue. Can I try it?

Yes of course, you may submit a PR

**Comment by harshithasudhakar** [comment]
Hi, @luahan77m are you still working on it?

**Comment by scwlkq** [comment]
![image](https://github.com/apache/eventmesh/assets/89067331/618e5b0d-8564-48dd-832c-4bef807818ba)
this class seems to be deprecated now, so this issue should be closed. @Pil0tXia

**Comment by Pil0tXia** [comment]
Closed as stale.
