### ISSUE TITLE
[Enhancement] contains() is a legacy method that is equivalent to containsValue()

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4022]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/547126fc-edd0-4ebf-850d-527e483ca2c8)
![image](https://github.com/apache/eventmesh/assets/91315508/0e6604c7-11ac-41ba-aa91-5c719e0223d8)
located at:
eventmesh-registry-plugin/eventmesh-registry-consul/src/main/java/org/apache/eventmesh/registry/consul/service/HeatBeatScheduler.java line 94
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/TcpClient.java line 190
analysis and explanation:
Hashtable.contains(Object) and ConcurrentHashMap.contains(Object) are legacy methods for testing if the given object is a value in the hash table. They are often mistaken for containsKey, which checks whether the given object is a key in the hash table.
If you intended to check whether the given object is a key in the hash table, use containsKey instead. If you really intended to check whether the given object is a value in the hash table, use containsValue for clarity.

### Describe the solution you'd like

change to use containsValue().

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sumitdethe27** [comment]
can i take this issue

**Comment by Alonexc** [comment]
> can i take this issue
Someone has already submitted a pr. are you interested in other issues?
