### ISSUE TITLE
[Enhancement] Decoupling connector and worker for events process

### ISSUE THREAD

**Issue by xwm1992** [apache/eventmesh#4035]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

The connector pulls the message and the worker sends the message is currently a synchronous operation, which needs to realize asynchronous decoupling and exception handling in the sending process.

### Describe the solution you'd like

The connector pulls the message and the worker sends the message is currently a synchronous operation, which needs to realize asynchronous decoupling and exception handling in the sending process.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by willimpo** [comment]
@xwm1992please assign to me

**Comment by xwm1992** [comment]
@willimpo you discuss your implementation under this issue or in wechat, thanks.

**Comment by willimpo** [comment]
@xwm1992 sure

**Comment by xwm1992** [comment]
@willimpo hi, how is this issue going？

**Comment by willimpo** [comment]
@xwm1992 hi，I am still coding with odd moments after work. I plan to submit a PR this week

**Comment by willimpo** [comment]
@xwm1992 I found that connector and worker already decoupled in SourceWorker.java. Sorry for the late.
![image](https://github.com/apache/eventmesh/assets/115852231/158016fc-989e-4c6b-8eb6-abb6910bc46e)

**Comment by xwm1992** [comment]
> @xwm1992 I found that connector and worker already decoupled in SourceWorker.java. Sorry for the late. ![image](https://user-images.githubusercontent.com/115852231/248556938-158016fc-989e-4c6b-8eb6-abb6910bc46e.png)

yes, the openfunction connector use this decoupling, so I submit the code, but if you have other plans, can also submit your pr

**Comment by Pil0tXia** [comment]
I assume this issue has been completed based on conversation.
