### ISSUE TITLE
[Bug] Caused by: Event message example error

### ISSUE THREAD

**Issue by nguyenminhtuanfit** [apache/eventmesh#4083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

i am facing this example and not able subscribe topic when running eventmesh example

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'subService' 
<img width="1379" alt="image" src="https://github.com/apache/eventmesh/assets/6532409/78d2ef58-feab-431a-b638-f69f3f2129cc">

### How to reproduce

- download apache-eventmesh-1.8.0-incubating then run ./start.sh
- run package org.apache.eventmesh.http.demo.sub.SpringBootDemoApplication under event-mesh-example

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
It seems that this bug has been resolved in the lastest version.
