### ISSUE TITLE
[Enhancement] Switching order: expected value, actual value.[MessageUtilsTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4085]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/1805d568-abb9-4edf-89d3-32bb02967ba8)

located at:
eventmesh-sdks/eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/common/MessageUtilsTest.java line 44,63,75,87,102,123,139,162,163
analysis and explanation:
The standard assertions library methods such as org.junit.Assert.assertEquals, and org.junit.Assert.assertSame expect the first argument to be the expected value and the second argument to be the actual value. For AssertJ, it’s the other way around, the argument of org.assertj.core.api.Assertions.assertThat is the actual value, and the subsequent calls contain the expected values. Swap them, and your test will still have the same outcome (succeed/fail when it should) but the error messages will be confusing.

### Describe the solution you'd like

swap these 2 arguments so they are in the correct order: expected value, actual value.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Kouzola** [comment]
Hi, 
I would like to implement that task pls.
Thank you

**Comment by Pil0tXia** [comment]
@Kouzola Welcome to EventMesh community.
