### ISSUE TITLE
[Enhancement] Anonymous new can be replaced with lambda.[AsyncSubClient]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/5d8e9ae3-d437-4d17-ac5d-6d0a251275c8)
located at:
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/AsyncSubClient.java line 43,49

### Describe the solution you'd like

replace with lambda. use the correct log format.
![image](https://github.com/apache/eventmesh/assets/91315508/968be312-18dc-4e82-9b9d-3bfc68dbe400)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kartiktayal** [comment]
I would like to work on this issue.

**Comment by harshithasudhakar** [comment]
@kartiktayal Sure, you may submit a PR.

**Comment by kartiktayal** [comment]
I have already attached a PR with this
