### ISSUE TITLE
[Enhancement] Anonymous new can be replaced with lambda.[BroadCastSubClient]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4088]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/9ff1bf6f-f4f1-49b3-a8ea-c6b36d86520d)
located at:
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/BroadCastSubClient.java line 43,50

### Describe the solution you'd like

replace with lambda. use the correct log format.
![image](https://github.com/apache/eventmesh/assets/91315508/ecb8220b-1111-4d1b-88f3-5f0a933781a8)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kartiktayal** [comment]
I would like to work on this issue

**Comment by roshan8084** [comment]
I would like to work on this issue. Can you please guide me . As it's my first time contributing in opensource projects.

**Comment by Pil0tXia** [comment]
@roshan8084 Welcome, you may fork EventMesh git repository and make changes mentioned in this issue. Then, submit a PR to merge your changes into master branch. For detailed instructions, please see https://eventmesh.apache.org/community/contribute/contribute.

**Comment by roshan8084** [comment]
I am sum not understanding in this issue how can i modify. it's my first time participates for open source project. please Can you guide me.

**Comment by Pil0tXia** [comment]
@roshan8084 You may take a look at Java Lambda expressions, it will be helpful: https://www.w3schools.com/java/java_lambda.asp
