### ISSUE TITLE
[Enhancement]  Anonymous new can be replaced with lambda.[SyncSubClient]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4091]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/561b1d9e-a14c-4671-9bc0-f726f44d431a)
located at:
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/SyncSubClient.java line 43,48

### Describe the solution you'd like

replace with lambda. use the correct log format.
![image](https://github.com/apache/eventmesh/assets/91315508/1ab40643-09ef-46a0-8df8-1cc7a4ace78a)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by storv** [comment]
I would love to do this! Thanks for the guide, I'll follow it and let you know my results. 😄

**Comment by Pil0tXia** [comment]
@storv Welcome to EventMesh community.

**Comment by storv** [comment]
@Pil0tXia hi,bro. i complete the  guide doc, maybe there is something wrong with me about the settings of the imports layout.  i need your help!!PLZ.
![image](https://github.com/apache/eventmesh/assets/5308762/bc826bb6-9d9e-435e-afb0-1035585b0cd8)

**Comment by Pil0tXia** [comment]
@storv You may check your IDEA `auto import` settings. It may automatically change import sequence. Also, you may check whether EventMesh CheckStyle Profile is `activated` in CheckStyle plugin panel.
