### ISSUE TITLE
[Enhancement] Use assertThat(actual).hasSize(expected) instead.

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4092]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/1599b568-c53c-4800-ad7d-7f1e80c30687)
located at:
eventmesh-sdks/eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumerTest.java line 136

### Describe the solution you'd like

![image](https://github.com/apache/eventmesh/assets/91315508/14598c85-a3d0-4f62-b048-0f9769280004)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sumitdethe27** [comment]
can i take this issue

**Comment by Alonexc** [comment]
Of course, very welcome.
