### ISSUE TITLE
[Enhancement] Local variable is redundant.

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4094]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/c12bbc81-8732-405c-8366-0b18259f6a2c)
![image](https://github.com/apache/eventmesh/assets/91315508/353ec680-286a-4dbb-93f2-94b5e9cbdabf)
![image](https://github.com/apache/eventmesh/assets/91315508/4b385de7-5ae9-444b-b917-d32d1bd29f71)
![image](https://github.com/apache/eventmesh/assets/91315508/5324abec-621f-41f8-b0e4-4c258e9a171b)
located at:
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/util/EventMeshClientUtil.java line 141,192,216,238

### Describe the solution you'd like

a. remove the redundant local variables.
![image](https://github.com/apache/eventmesh/assets/91315508/be26b637-c03a-42c6-92ad-a1c09a9b1463)

b. remove useless curly braces around statement
![image](https://github.com/apache/eventmesh/assets/91315508/1fe0b51f-e699-4158-8e32-67ca7e5bb268)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by VishalMCF** [comment]
The class mentioned is not present in the entire project

**Comment by Alonexc** [comment]
@VishalMCF  Yes, it has been removed due to a code update and I will close this issue.
