### ISSUE TITLE
[Enhancement] Code optimization. [EtcdCustomService]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4095]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/39a749e7-1247-4ccf-a950-2ee15fde2b4e)
![image](https://github.com/apache/eventmesh/assets/91315508/2c5b0956-fa1a-45e6-82c4-7bbe58f37538)
![image](https://github.com/apache/eventmesh/assets/91315508/17157ce2-131e-4690-aa4d-b7fe80ff808f)
analysis and explanation:
a. InterruptedExceptions should never be ignored in the code, and simply logging the exception counts in this case as "ignoring". The throwing of the InterruptedException clears the interrupted state of the Thread, so if the exception is not handled properly the information that the thread was interrupted will be lost. Instead, InterruptedExceptions should either be rethrown - immediately or after cleaning up the method’s state - or the thread should be re-interrupted by calling Thread.interrupt() even if this is supposed to be a single-threaded application. Any other course of action risks delaying thread shutdown and loses the information that the thread was interrupted - probably without finishing its task.
b. Declaring a variable only to immediately return or throw it is a bad practice.
Some developers argue that the practice improves code readability, because it enables them to explicitly name what is being returned. However, this variable is an internal implementation detail that is not exposed to the callers of the method. The method name should be sufficient for callers to know exactly what will be returned.

### Describe the solution you'd like

a. restore interrupted state
![image](https://github.com/apache/eventmesh/assets/91315508/689337c8-3841-47c2-b3a4-ea430bc43d4f)

b. inline variable
![image](https://github.com/apache/eventmesh/assets/91315508/628957bc-4216-44a6-bea4-6468f8dbe369)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by himansh295** [comment]
@xwm1992 Can I work on this issue  ?

**Comment by Alonexc** [comment]
sure
