### ISSUE TITLE
[Enhancement] Method may fail to clean up stream or resource[WatchFileManagerTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4098]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/4129c5d0-fbbb-4dad-8f1e-5eaf54c6782e)
located at:
eventmesh-common/src/test/java/org/apache/eventmesh/common/file/WatchFileManagerTest.java line 54,56
analysis and explanation:
The method creates an IO stream object, does not assign it to any fields, pass it to other methods that might close it, or return it, and does not appear to close the stream on all paths out of the method.  This may result in a file descriptor leak.  It is generally a good idea to use a finally block to ensure that streams are closed.

### Describe the solution you'd like

use try-with-resources to manage resources.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Ht12137** [comment]
I am new to the community,can i solve the problem?

**Comment by NiuXiangQian** [comment]
As a newbie, I would love to try to complete this fix job.

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh/pull/4716.
