### ISSUE TITLE
[Enhancement] Field may be 'final'[UpStreamMsgContext]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4102]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/45202cc0-3e7e-48cf-8d9f-12c8c2878dbb)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/UpStreamMsgContext.java line 46,48,50,52,54

### Describe the solution you'd like

add final

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kuldeepsidhu88** [comment]
@Alonexc Can you please assign this to me, I can work on it.

**Comment by Alonexc** [comment]
welcome
