### ISSUE TITLE
[Enhancement] Do some code optimization.[PushContext]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4106]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/454b8923-c7c2-4bd7-98d5-231f8120bb2a)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/PushContext.java line 34,36,38,40,42
analysis and explanation:
a. Field may be 'final'
b. Make deliveredMsgsCount a static final constant or non-public and provide accessors if needed.

### Describe the solution you'd like

![image](https://github.com/apache/eventmesh/assets/91315508/e3a1d61f-b7db-4cb0-a101-520080a63650)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Raunak445** [comment]
Hi,
I wanted to know if this issue is closed or not .
If not I would like to work on it.

**Comment by Alonexc** [comment]
@Raunak445 Hi, this issue has been fixed, are you interested in other issues? Your message is welcome.

**Comment by Raunak445** [comment]
Yeah, sure if there are other good for first issues , kindly suggest them to me.
