### ISSUE TITLE
[Enhancement] Do some code optimization.[DownStreamMsgContext]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4107]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/781763e4-6cd4-4669-929b-1628d2d35df2)
![image](https://github.com/apache/eventmesh/assets/91315508/5d550c02-92e9-44d4-a3c9-408895e96787)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/DownStreamMsgContext.java line 50,52,55,63

### Describe the solution you'd like

![image](https://github.com/apache/eventmesh/assets/91315508/73e99780-23c5-446f-835e-de46d8b9ee77)
![image](https://github.com/apache/eventmesh/assets/91315508/b916fe2d-308e-42b9-a7ae-b13c03fffd43)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dipankr** [comment]
Hello, I'd like to work on this and similar issues

**Comment by Alonexc** [comment]
ok!
