### ISSUE TITLE
[Enhancement] Field may be 'final'[EventMeshRebalanceService]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4108]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/9061b70b-f11c-4cc9-aeaa-18ccbc758bb1)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/rebalance/EventMeshRebalanceService.java line 35,37,39

### Describe the solution you'd like

add final.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kuldeepsidhu88** [comment]
@Alonexc I can work on this.

**Comment by Alonexc** [comment]
@kuldeepsidhu88 Ok! Welcome to eventmesh community.
