### ISSUE TITLE
[Enhancement] Do some code optimization.[ClientGroupWrapper]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4109]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/11700540-4645-4f27-bd5f-b0b28963b2dc)
![image](https://github.com/apache/eventmesh/assets/91315508/ea9341be-b4f6-4db8-9249-678fbcde3509)
![image](https://github.com/apache/eventmesh/assets/91315508/97ae10de-f457-477d-b337-0fb9a00dafe2)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java line 91-101,112,141,220,269,335,362,391,417

### Describe the solution you'd like

![image](https://github.com/apache/eventmesh/assets/91315508/937e3e62-58a7-4cb9-bd38-d288468658b5)
![image](https://github.com/apache/eventmesh/assets/91315508/7e5887c4-23ba-4b7d-874f-6fac88342e0a)

restore interrupted state:
![image](https://github.com/apache/eventmesh/assets/91315508/4023b486-528e-4ea5-8fa2-80e04c3e0b30)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nitheesh-daram** [comment]
Hey team,
I would like to work on this.

thanks

**Comment by Alonexc** [comment]
@nitheesh-daram Welcome to eventmesh community！
