### ISSUE TITLE
[Enhancement] InterruptedExceptions should never be ignored in the code.[HttpRetryer]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4110]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/4cd35053-858d-4fd4-b9d8-b4d946fffc09)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/retry/HttpRetryer.java line 85
analysis and explanation:
InterruptedExceptions should never be ignored in the code, and simply logging the exception counts in this case as "ignoring". The throwing of the InterruptedException clears the interrupted state of the Thread, so if the exception is not handled properly the information that the thread was interrupted will be lost. Instead, InterruptedExceptions should either be rethrown - immediately or after cleaning up the method’s state - or the thread should be re-interrupted by calling Thread.interrupt() even if this is supposed to be a single-threaded application. Any other course of action risks delaying thread shutdown and loses the information that the thread was interrupted - probably without finishing its task.

### Describe the solution you'd like

restore interrupted state
![image](https://github.com/apache/eventmesh/assets/91315508/ac48449c-9056-419d-86ab-dacf85c7c0b9)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
I want to fix this issue! Please assign it to me. Thanks.

**Comment by Alonexc** [comment]
@Pil0tXia Ok, welcome to the eventmesh community.
