### ISSUE TITLE
[Enhancement] Do some code optimization.[AsyncHTTPPushRequest]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4111]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/95cbc5da-dc0d-4e21-ac09-13f57679fe43)
![image](https://github.com/apache/eventmesh/assets/91315508/f41df215-6643-4e1f-a625-0e565621c7d9)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java line 331,343
analysis and explanation:
a. Method invocation 'get' may produce 'NullPointerException'
b. Catch Exception instead of Throwable.

### Describe the solution you'd like

a. use Objects.requireNonNull() to avoid NPE.
b. use Exception instead of Throwable.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by himansh295** [comment]
@Alonexc Can i work on this issue

**Comment by Alonexc** [comment]
@himansh295 You are very welcome to pr.
