### ISSUE TITLE
[Enhancement] change the null reference to empty object in UrlMappingPattern.java

### ISSUE THREAD

**Issue by nikam14** [apache/eventmesh#4136]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Null is a reference that does not point to any object.
returning an empty object can help to improve the readability and maintainability of code

### Describe the solution you'd like

location - eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/util/UrlMappingPattern.java
line - 63
expected-
![1](https://github.com/apache/eventmesh/assets/55378196/5718357e-f82a-40cf-a19e-da24a50efc7e)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by heliang666s** [comment]
hello,I am new in there,I will try it,please assign me,thanks~

**Comment by Pil0tXia** [comment]
@heliang666s Welcome! This issue is open for contribution.

**Comment by Pil0tXia** [comment]
Closed according to https://github.com/apache/eventmesh/pull/4846#issuecomment-2158176436.
