### ISSUE TITLE
[Enhancement] Do some code optimization.[StreamPushRequest]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4191]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/d916c545-b6a2-44ba-a6d3-cbd8ab4437c7)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/StreamPushRequest.java line 104-111,115-122

### Describe the solution you'd like

a. repeat code extraction as a method
b. use switch instead.
![image](https://github.com/apache/eventmesh/assets/91315508/78bea3ed-8918-4884-8693-2e7f9874e6d9)
![image](https://github.com/apache/eventmesh/assets/91315508/4db2ec93-b092-4269-98a3-72046ea2346a)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by himansh295** [comment]
@Alonexc Can I work on this Issue ?

**Comment by Pil0tXia** [comment]
@himansh295 Welcome. You may submit a PR.
