### ISSUE TITLE
[Enhancement] Dereference of 'subscriptionItems' may produce NPE.

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4196]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/a4a0cffa-de0d-46a3-8305-346a11abd2f3)
![image](https://github.com/apache/eventmesh/assets/91315508/ab24f2c4-af58-4d62-babf-50ab0e5b75bc)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/SubscribeStreamProcessor.java line 54.98,151
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/UnsubscribeProcessor.java line 75

### Describe the solution you'd like

add `static` and use Objects.requireNonNull() to avoid NPE.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by vaibhavarya1622** [comment]
Hi, Can you please assign the issue? I would like to work on it.

**Comment by Alonexc** [comment]
@vaibhavarya1622 Of course, welcome to the evnetmesh community.
