### ISSUE TITLE
[Enhancement] Change to use switch instead of if-else.

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4197]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/47d2a1fd-e94d-4849-8f47-8caf1fbcde10)
![image](https://github.com/apache/eventmesh/assets/91315508/a328a922-b803-49f9-b171-39ce4a7e4024)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/WebhookPushRequest.java line 191,204-208,240-247,251-258
analysis and explanation: 
It is more efficient to use switch than if-else in making judgments for Enum types.

### Describe the solution you'd like

use switch instead.
![image](https://github.com/apache/eventmesh/assets/91315508/50c548f5-7ba3-4001-abaa-1ce1433862ee)
![image](https://github.com/apache/eventmesh/assets/91315508/8965c9a1-9172-4e1c-8b6e-8b74fb5e730f)
![image](https://github.com/apache/eventmesh/assets/91315508/7793184f-af36-41dd-827c-e112ab55a98f)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kartiktayal** [comment]
I would like to pick this task :hand:

**Comment by kartiktayal** [comment]
For below line,
[https://github.com/apache/eventmesh/blob/master/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/WebhookPushRequest.java#L190](url)
I am getting the sonar validation error that there should be more conditions to use switch case and it is better to use if statement since we only have one condition.

**Comment by Alonexc** [comment]
@kartiktayal Hello and welcome to the eventmesh community, welcome contributions.

**Comment by Alonexc** [comment]
Hi, where is the modification? I did not understand, line 190?

**Comment by kartiktayal** [comment]
> Hi, where is the modification? I did not understand, line 190?

For line 190, since there is only one condition, I was getting a sonar warning that it is better to use if else statement instead of switch case

**Comment by Alonexc** [comment]
Ohhh, that doesn't need to be changed to switch.

**Comment by kartiktayal** [comment]
> Ohhh, that doesn't need to be changed to switch.

I am open for another task as well if this is done.

**Comment by Alonexc** [comment]
You are very welcome to contribute to eventmesh!
