### ISSUE TITLE
[Enhancement] Catch Exception instead of Throwable.

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4199]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/aef593ef-c072-42a8-accf-81185e5bf3ee)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/EventEmitter.java line 37,45,53
analysis and explanation:
Throwable is the superclass of all errors and exceptions in Java. Error is the superclass of all errors, which are not meant to be caught by applications.
Catching either Throwable or Error will also catch OutOfMemoryError and InternalError, from which an application should not attempt to recover.

### Describe the solution you'd like

Use `Exception` instead of `Throwable`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Codeprh** [comment]
Let me try to contribute

**Comment by Alonexc** [comment]
@Codeprh Welcome to eventmesh!
