### ISSUE TITLE
[Enhancement] Do some code optimization.[metrics]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4201]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/0ce3a123-ab0c-4067-9274-4b199e0d26ac)
![image](https://github.com/apache/eventmesh/assets/91315508/047b696c-853f-4da1-ba78-f7d995431793)
![image](https://github.com/apache/eventmesh/assets/91315508/6efd02c3-4c77-427a-9133-af2bfb8c2262)
![image](https://github.com/apache/eventmesh/assets/91315508/ea2e1658-5d1c-48a5-ae2d-aebf4f31b92e)
located at:
eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics PrometheusGrpcExporter PrometheusHttpExporter PrometheusTcpExporter
eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/utils/PrometheusExporterUtils.java line 73
analysis and explanation:
a. Field 'paramPairs' may be 'final'
b. Non-static initializers are rarely used, and can be confusing for most developers because they only run when new class instances are created. When possible, non-static initializers should be refactored into standard constructors or field initializers.
c. Local variable 'array' is redundant

### Describe the solution you'd like

a.add final
![image](https://github.com/apache/eventmesh/assets/91315508/abcc142c-9eb6-41e1-9de6-f75af4312bb4)
b. Use another way to initialize this instance
![image](https://github.com/apache/eventmesh/assets/91315508/ba18af86-c772-4be0-ba3a-d4bc43a537e7)
c.inline variable
![image](https://github.com/apache/eventmesh/assets/91315508/d8a8715b-233b-4ae4-a42e-77cb374eadb2)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Sourav-Kumar-Panda** [comment]
Can I work on this issue?

**Comment by Pil0tXia** [comment]
@Sourav-Kumar-Panda 
Of course. Welcome to EventMesh community. You may submit your code in a PR.

**Comment by Pil0tXia** [comment]
Typically, you have the permission to submit PRs directly, without additional assign.

**Comment by luahan77m** [comment]
Hi @Pil0tXia, can you assign this to me? I want to try it?

**Comment by Pil0tXia** [comment]
@luahan77m You already have permission to submit a PR directly.
