### ISSUE TITLE
[Enhancement] Do some code optimization.[EventMeshTcpMessageDispatcher]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4203]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/4aacda00-0200-4912-9d36-fc3e86e01f94)
![image](https://github.com/apache/eventmesh/assets/91315508/a7b67614-b622-4abc-adbe-c1b4138a4972)
![image](https://github.com/apache/eventmesh/assets/91315508/c078d427-4c4d-4e5d-86d4-34a42ee28eb9)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcpMessageDispatcher.java line 58,89-105,139-145
analysis and explanation:
a. Field 'eventMeshTCPServer' may be 'final'
b. use switch instead.
c. Replace this if-then-else statement by a single return statement.
Condition 'cmd != null' covered by subsequent condition 'Command.REQUEST_TO_SERVER == cmd || Command.ASYNC_MESSAGE_TO_SERVER == cmd || Command.BROADCAST_MESS ...'

### Describe the solution you'd like

a.add final
![image](https://github.com/apache/eventmesh/assets/91315508/d204e7c1-1775-4efd-ac47-d398302b3e58)
b. use switch instead.
![image](https://github.com/apache/eventmesh/assets/91315508/c717f912-ca80-400d-a5f1-fe4fcd5148d7)
c. 'if' statement can be simplified
![image](https://github.com/apache/eventmesh/assets/91315508/2d2b2186-f066-4909-823a-fd1a923a4450)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Codeprh** [comment]
I want to fix this issue! Please assign it to me. Thanks.

**Comment by Alonexc** [comment]
Of course, you're very welcome, and you can start by submitting a pr.

**Comment by HattoriHenzo** [comment]
@Codeprh are you still working on this?

**Comment by shubhamind08** [comment]
I want to work on the issue. Please assign me.

**Comment by HattoriHenzo** [comment]
@shubhamind08 you can submit a pull request.

**Comment by Alonexc** [comment]
@HattoriHenzo Okay, you can start by submitting a pr.

**Comment by vaibhavarya1622** [comment]
@shubhamind08  are you still working on this?

**Comment by Alonexc** [comment]
@shubhamind08 The task cycle is two weeks overdue and other contributors are welcome to complete it.
