### ISSUE TITLE
[Question]  event.getExtension(ProtocolKey.ClientInstanceKey.TOKEN) get null

### ISSUE THREAD

**Issue by misswolf** [apache/eventmesh#4209]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

i am running htt demos,
curl --location --request POST 'http://127.0.0.1:10105/eventmesh/publish/TEST-TOPIC-HTTP-ASYNC' \
--header 'token: 234324324' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "admin",
    "pass": "12345678"
}'
can't get repnose.
The server throw null exception on class SendAsyncEventProcessor 
**final String token = String.valueOf(event.getExtension(ProtocolKey.ClientInstanceKey.TOKEN))**
can't find any put ProtocolKey.ClientInstanceKey.TOKEN value to map.

how to run full http demos?

**Comment by pandaapo** [comment]
Would you be willing to submit a PR to properly handle the null here?
