### ISSUE TITLE
[Enhancement] Some optimizations to GrpcEventMeshCloudEventProtocolResolver.

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4267]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/07e25a9c-ba02-4063-8fe3-797e2d544339)
![image](https://github.com/apache/eventmesh/assets/91315508/83934183-f6e9-4b6e-ae02-77cc361ebeb7)
located at:
eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/grpc/GrpcEventMeshCloudEventProtocolResolver.java line 43,51,60
analysis and explanation:
a. Immediately return this expression instead of assigning it to the temporary variable "event".
b. Method invocation 'deserialize' may produce 'NullPointerException'

### Describe the solution you'd like

Inline variable and use Objects.requireNonNull()
![image](https://github.com/apache/eventmesh/assets/91315508/35864e11-8a07-4b59-9d53-11b081913ebb)
![image](https://github.com/apache/eventmesh/assets/91315508/9cd8db7a-6180-4716-b330-0ea9e7726a9c)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by devCod3r** [comment]
Hello, I would like to work on this. Please assign this issue to my name. Thank you!!

**Comment by Alonexc** [comment]
@devCod3r ok! You can submit the pr first.
