### ISSUE TITLE
[Enhancement] Use switch to replace the if-else.[CloudEventsProtocolAdaptor]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4268]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/ae161634-e157-46fb-a291-cc9cd95a5fb0)
![image](https://github.com/apache/eventmesh/assets/91315508/8aa56b52-a677-4b2d-818f-dbc8fa26c5ba)
located at:
eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/CloudEventsProtocolAdaptor.java line 92-102,120-150

### Describe the solution you'd like

![image](https://github.com/apache/eventmesh/assets/91315508/8ac8d86d-6726-4d3c-afb5-522dd2cca86c)
![image](https://github.com/apache/eventmesh/assets/91315508/69f2a500-6bab-44d3-aec5-5a662859e57c)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by devCod3r** [comment]
Hello, I would like to work on this. Please assign this issue to my name. Thank you!!

**Comment by Alonexc** [comment]
OK! You can submit the pr first.

**Comment by hanshal101** [comment]
PR made #4303
