### ISSUE TITLE
[Enhancement] Use switch to replace the if-else.[MeshMessageProtocolAdaptor]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4269]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/f2e21fa4-39c8-4bc6-baca-d240132a2668)
![image](https://github.com/apache/eventmesh/assets/91315508/42ec432e-6b68-45ea-ba3a-7792665a4750)
located at:
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/MeshMessageProtocolAdaptor.java line 83-93,113-136

### Describe the solution you'd like

![image](https://github.com/apache/eventmesh/assets/91315508/5ff536bb-832a-4e3b-87e6-7975e825b5a7)
![image](https://github.com/apache/eventmesh/assets/91315508/814ca25b-264a-48d2-b991-84e78a719a4a)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by devCod3r** [comment]
Hello, I would like to work on this. Please assign this issue to my name. Thank you!!
