### ISSUE TITLE
[Question] Which type of server is the default?

### ISSUE THREAD

**Issue by silentchildh** [apache/eventmesh#4300]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

In the `eventmesh-runtime/conf/eventmeshproperties` file, If do not fill `eventMesh.server.provide.protocols`, eventmesh will specify the default server for the user.
![image](https://github.com/apache/eventmesh/assets/122422744/e65ac1c8-51a6-442e-96ef-67f33096d0bc)

But I found that there might be some conflicts in the code.

- Here will specify EventMeshHTTPServer:
![image](https://github.com/apache/eventmesh/assets/122422744/2a5983e4-ef74-4c83-b208-06223932eda1)
(located at: eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java  line 124)

- But EventMeshTcpServer specified here：
![image](https://github.com/apache/eventmesh/assets/122422744/1ab107c1-4245-497e-be15-07efe99eeba5)
(Located at: eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java line 97)

Actually, it will be use `EventMeshHTTPServer` ,if not specify  protocol in  `eventmesh.properties`.If `eventMesh.server.provide.protocols` fills in not all uppercase characters, or any other characters, and will use `EventMeshTcpServer` as the default server.
![image](https://github.com/apache/eventmesh/assets/122422744/c194964e-5cda-47b3-bf99-d20c40526efa)
(Located at: eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java line 78)

Therefore, which server is eventmesh wants to be the default server.

**Comment by silentchildh** [comment]
In the logic of the third picture, in `eventmesh.properties`,if `eventMesh.server.provide.protocols` 'fills in not all uppercase characters, or any other characters, and will use TCP as the default server.
![](https://user-images.githubusercontent.com/122422744/256746883-c194964e-5cda-47b3-bf99-d20c40526efa.png)

**Comment by Pil0tXia** [comment]
`eventMesh.server.provide.protocols=` -> HTTP
`eventMesh.server.provide.protocols=http` -> TCP

**Comment by silentchildh** [comment]
> `eventMesh.server.provide.protocols=` -> HTTP `eventMesh.server.provide.protocols=http` -> TCP

Why not just use one protocol as the default server instead of two?

**Comment by Pil0tXia** [comment]
@silentchildh Because the vast majority of users will not use only one protocol, if the user has misconfigured the protocol (e.g. case mismatch, incorrect punctuation), the fact that EventMesh starts up with only the most basic TCPServer will make it easier for the user to be aware of the configuration error.

**Comment by silentchildh** [comment]
> @silentchildh Because the vast majority of users will not use only one protocol, if the user has misconfigured the protocol (e.g. case mismatch, incorrect punctuation), the fact that EventMesh starts up with only the most basic TCPServer will make it easier for the user to be aware of the configuration error.

So what you're saying is, split into multiple errors, and alert the user to different errors by eventually starting the HTTP and TCP servers differently. But will this increase the cost of memory for users?

**Comment by Pil0tXia** [comment]
@silentchildh It won't increase the cost of memory for users. If one day this practice proves unsuitable, we'll find a better way.

Yes, you may use `toUpperCase()` method to avoid case conversion problems.

**Comment by silentchildh** [comment]
@Pil0tXia Well, thank you for taking part in this discussion.

**Comment by Pil0tXia** [comment]
@silentchildh You're welcome, and thanks for providing us with feedback on your usage. Please feel free to close issue if your problem is solved.
