### ISSUE TITLE
[Feature] Support zookeeper as meta storage

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#4375]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Support zookeeper as meta storage

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by Ceilzcx** [comment]
may I ask if this is not what the event-registry-zookeeper module does this feature?

**Comment by xwm1992** [comment]
> may I ask if this is not what the event-registry-zookeeper module does this feature?

The registry module will be migrated to the meta module and support the functions of the meta module. You can refer to the meta implementation of nacos and etcd. @Ceilzcx

**Comment by jihuayu** [comment]
I noticed that the code [ZookeeperMetaService](https://github.com/apache/eventmesh/blob/master/eventmesh-meta/eventmesh-meta-zookeeper/src/main/java/org/apache/eventmesh/meta/zookeeper/service/ZookeeperMetaService.java) has already implemented meta-zookeeper. Has this issue been resolved?
