### ISSUE TITLE
[Feature] Support consul as meta storage

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#4376]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Support consule as meta storage

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by HattoriHenzo** [comment]
@qqeasonchen hello, is there a design document or a documentation to follow the design and implementation?

**Comment by Pil0tXia** [comment]
@HattoriHenzo Here is the arch:

![image](https://github.com/apache/eventmesh/assets/41445332/637d24d4-a30b-434e-8da0-25c02ebd6422)

![image](https://github.com/apache/eventmesh/assets/41445332/3001c2ee-a688-446a-87c7-e4345d15592e)
