### ISSUE TITLE
[Question] Does rabbitmq storage only support a single routingkey configuration

### ISSUE THREAD

**Issue by cocoandgaga** [apache/eventmesh#4397]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question
rabbitmq-client.properties only support a single exchangeName,routingkey,and queueName configuration. I want to subscribe using exchangeName,queueName  and routingkey and callback url。but, I can't understand how to config .

**Comment by cocoandgaga** [comment]
> 

Thank you for your answer！According to what you said, what I need is the connect plugin？In service A, if eventMesh SDK is used to send a message to eventMesh. And the connection plugin type is rabbitmq, sinkEnable is turned on. Is it possible to call the api of service B when eventMesh sending messages to the rabbitmq？

**Comment by cocoandgaga** [comment]
> Because storage-plugin takes on the role of a queue inside eventmesh, not a connector, it was designed to be used without multiple queues. Thus, the existing exchange and queue in rabbitmq-storage-plugin are both singular and fixed.
> 
> You may create a `eventmesh.default` exchange, a `DefaultQueue` queue, and bind both of them with `#` routingkey (to redirect all msgs `eventmesh.default` received to `DefaultQueue`) in rabbitmq, then fill in the same settings in `rabbitmq-client.properties`.
> 
> In my case, I use these configurations, and I can send messages normally, and I didn't use the `callback url`. If these configurations can't satisfy your usage scenario, can you please tell me more about your need for `callback url`? Similarly, you can also describe your need for multiple queues if necessary.
> 
> By the way, if you have encountered any bugs in the use, you are welcome to feedback to us; if you have not encountered bugs, you are also welcome to leave a message under this PR #4394.

Thank you for your answer！According to what you said, what I need is the connect plugin？In service A, if eventMesh SDK is used to send a message to eventMesh. And the connection plugin type is rabbitmq, sinkEnable is turned on. Is it possible to call the api of service B when eventMesh sending messages to the rabbitmq？

**Comment by Pil0tXia** [comment]
@cocoandgaga Yes, RabbitMQ connectors has been merged into master branch yesterday. In EventMesh, we usually have senders (service A) in one side (source workers) and receivers in another side (sink workers), and the messages sent by service A are delievered to service B, which is a one-way `delivery` and differs from `web request`. We call this model the unanticipated MQ model, meaning that the sender doesn't expect a response from the receivers, and this model is used by most MQs.

In your case, you may need another publish/subscribe relationship to make service A the receiver and service B the sender (reverse the former one), or you may customize your message and response logic (e.g. callback URL in message body) to send responses to service A directly.
