### ISSUE TITLE
[Feature] Support subscription info management on Dashboard

### ISSUE THREAD

**Issue by lrhkobe** [apache/eventmesh#4400]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Provide visual support for eventmesh subscription information management on the dashboard.

### Components Interaction Diagram
![dashboard(1)](https://github.com/apache/eventmesh/assets/34571087/f61103a8-e9a4-419f-ab42-ae99feb4f431)

### Management Interface in EventMesh

- create topic 

```
http://127.0.0.1:10105/eventmesh/topic/create
Request Method：Post
Params：application/json
{
	"topic":"topic1;topic2"
}

Result：
{
	"retMessage":"success",
	"retCode":0
}
```

- delete topic
```
http://127.0.0.1:10105/eventmesh/topic/delete
Request Method：Post
Params：application/json
{
	"topic":"topic1;topic2"
}

Result：
{
	"retMessage":"success",
	"retCode":0
}
```

- query subscription

```
http://127.0.0.1:10105/eventmesh/subscrition/query
Request Method：Get

Result：
{
	"localTopicSet": ["topic1"],
	"subsrciption": [{
		"consumerGroup": "consumer-group-1111-AB0",
		"topic": "topic1",
		"subscriptionItem": {
			"topic": "topic1",
			"mode": "CLUSTERING",
			"type": "ASYNC"
		},
		"idcUrls": {
			"idc": ["http://127.0.0.1:8088/sub/test"]
		},
		"urls": ["http://127.0.0.1:8088/sub/test"],
		"httpAuthTypeMap": {				
		}
	}]
}
```

- subscribe

```
http://127.0.0.1:10105/eventmesh/subscribe/local
Request Method：Post
Params：application/json

{
	"url":"http://127.0.0.1:8088/sub/test",
	"consumerGroup":"group1",
	"topic":[{
			"mode":"CLUSTERING",
			"topic":"topic1",
			"type":"ASYNC"
	}]
}

Result：
{
	"retMessage": "success",
	"retCode": 0
}
```

- unsubscribe

```
http://127.0.0.1:10105/eventmesh/unsubscribe/local
Request Method：Post
Params：application/json
{
	"url":"http://127.0.0.1:8088",
	"consumerGroup":"group1",
	"topic":["topic1"]
}

Result：
{
	"retMessage": "success",
	"retCode": 0
}
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by Pil0tXia** [comment]
Backend doc: https://docs.qq.com/doc/DSk9NU1JiRlBpSXln

**Comment by Pil0tXia** [comment]
Progress: https://tencentmeeting.txdocs.qq.com/doc/DSUVsanZTWHh6cUVt
