### ISSUE TITLE
[Feature] Add Wechat sink connector

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#4410]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Wechat sink connector

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by wizardzhang** [comment]
@qqeasonchen i'm interest in this issue, but i'm confused，like dingtalk and wecom both use robot to sink message，what
wechat can use to sink message，Official account？can u give me some suggestion？

**Comment by wizardzhang** [comment]
> > @qqeasonchen i'm interest in this issue, but i'm confused，like dingtalk and wecom both use robot to sink message，what wechat can use to sink message，Official account？can u give me some suggestion？
> 
> After registering a WeChat developer account according to the official WeChat development documentation, one way is to use HttpClient to send messages to WeChat.

ok，thk for you advice，i will do some research on it
