### ISSUE TITLE
[Feature] Add Springboot sink connector

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#4414]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Add Springboot sink connector

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by HattoriHenzo** [comment]
@qqeasonchen for Spring Boot is it an autoconfiguration library to be used to connect to EventMesh? I don't understand how Spring Boot can be a Sink or a Connector?

**Comment by yanrongzhen** [comment]
I'm willing to work on this issue.
