### ISSUE TITLE
[Feature] Add Slack sink connector

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#4419]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Add Slack sink connector

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by HattoriHenzo** [comment]
@qqeasonchen Does Slack shouldn't have a **source** connector?

**Comment by jihuayu** [comment]
I want to try this task. I will send a PR later.
