### ISSUE TITLE
[Feature] Add Feishu sink connector

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#4420]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Add Feishu sink connector

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by SunnyBoy-WYH** [comment]
hi，as we know ,feishu is a chat tool , this issue expected  send msg card for notification?

**Comment by xwm1992** [comment]
> hi，as we know ,feishu is a chat tool , this issue expected send msg card for notification or feishu table?
the Feishu sink connector expected send msg to Feishu Bot, which you can get the webhook config of Feishu Bot and using in the sink connector.

**Comment by SunnyBoy-WYH** [comment]
> > hi，as we know ,feishu is a chat tool , this issue expected send msg card for notification or feishu table?
> 
> The Feishu sink connector expected send msg to Feishu Bot, which you can get the webhook config of Feishu Bot and using in the sink connector.

i see the feishu openapi doc, after send msg to bot，bot will send msg to somebody or group？ it need user's id ,where we expected config the user's id(tell the bot we expected send to whom)?

**Comment by Pil0tXia** [comment]
@SunnyBoy-WYH Yes, the message destination is required if necessary.

**Comment by SunnyBoy-WYH** [comment]
if no required ddl, can you assign it to me temporarily?

**Comment by Pil0tXia** [comment]
You may submit a PR.

**Comment by Pil0tXia** [comment]
@SunnyBoy-WYH SDK and OpenAPI are both OK, however it is not recommended to add code to `runtime` that only a certain connector will use.

**Comment by xwm1992** [comment]
> > @SunnyBoy-WYH SDK and OpenAPI are both OK, however it is not recommended to add code to `runtime` that only a certain connector will use.
> 
> ok, maybe we can use okhttp? and how can we connectRecord transfer to feishu msg? just let connectRecord.getData() as feishu message ?

yes, you can treat the data as feishu message.
