### ISSUE TITLE
[Enhancement]Uniformly manage duplicate static variables

### ISSUE THREAD

**Issue by mxsm** [apache/eventmesh#4474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Existing code has many duplicate static variables, and it is desired to organize them into a common module for unified maintenance.

### Describe the solution you'd like

For example:
![image](https://github.com/apache/eventmesh/assets/15797831/3c7a2f17-3a3f-4157-9353-b92726c5e371)
![image](https://github.com/apache/eventmesh/assets/15797831/d18762e0-d29b-4078-8b18-657258d34409)
Cloudevents exist in both classes. We can categorize and organize static variables like this in the project. If it is used in multiple modules, it can be moved to the common module.Make the code look cleaner and easier to maintain uniformly.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by VishalMCF** [comment]
Hi Can I work on this issue??

**Comment by mxsm** [comment]
> Hi Can I work on this issue??

@VishalMCF  Sure, Welcome! I will assign it to you

**Comment by VishalMCF** [comment]
@mxsm  Hello,  I am not able to find many duplicate static variables. Whatever I have found for that I have made the changes which you can find in the pull request which I am going to raise shortly.

**Comment by mxsm** [comment]
this issue has fixed, PR #4495   I will closed it.

**Comment by VishalMCF** [comment]
@mxsm Hi, I just wanted to say that this was the second issue I worked on. Although no contribution is a small contribution I believe that I can contribute to the core development of Apache Eventmesh. I am very much interested in the development of NodeJS SDK for Eventmesh. But when that begins (as it is currently planned) I have to be familiar with the majority of the codebase of Apache Eventmesh. In case if you have any suggestions then please let me know. I will be going through the documentation and merged pull requests to get better clarity. But still wanted to know your opinion if you can provide. Thanks!!

**Comment by Pil0tXia** [comment]
@VishalMCF You may start with deploying a connector and running `examples`.

**Comment by mxsm** [comment]
> @mxsm Hi, I just wanted to say that this was the second issue I worked on. Although no contribution is a small contribution I believe that I can contribute to the core development of Apache Eventmesh. I am very much interested in the development of NodeJS SDK for Eventmesh. But when that begins (as it is currently planned) I have to be familiar with the majority of the codebase of Apache Eventmesh. In case if you have any suggestions then please let me know. I will be going through the documentation and merged pull requests to get better clarity. But still wanted to know your opinion if you can provide. Thanks!!

@VishalMCF 

1. You can get an overview of the entire project's code architecture and the relationships between each module.

2. Choose a protocol, like making gRPC calls, and familiarize yourself with making gRPC calls corresponding to the examples module. This will help you understand how the entire EventMesh system interacts and provide insights into its internal workings.

3. Once you've grasped the internal implementation, you can start writing an SDK for Node.js based on your interests. You can refer to the Java SDK as a guide. As you've seen with the Rust SDK, I developed it based on the Java SDK. However, you're also free to make improvements and optimizations based on your own insights.
