### ISSUE TITLE
[Enhancement] Standardize exception handling in tests

### ISSUE THREAD

**Issue by mureinik** [apache/eventmesh#4483]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Most of the tests in the project were written prior to JUnit 4.13, and use some older idioms instead of using the modern `assertThrows`. Following up on #4475, JUnit Jupiter offers some more elegant options.

### Describe the solution you'd like

- There is no need to catch an exception and explicitly fail the test. The test should be allowed to throw the exception and error-out, which is technically the correct behavior (the test didn't really fail on any logic test).

- In order to test cases when an exception must be thrown, `Assertions.assertThrows` can be used. There is no need to catch the exception assert it is not `null`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by mureinik** [comment]
@mxsm please note the post-merge build failed. This seems unrelated to the PR itself, though - the CI is attempting to push to dockerhub and failing to login there:
https://github.com/apache/eventmesh/actions/runs/6518199356/job/17703384073

**Comment by Pil0tXia** [comment]
@mureinik Yes, it's an issue WIP.
