### ISSUE TITLE
[Enhancement] Optimizing Log Printing Using the LogUtils

### ISSUE THREAD

**Issue by mxsm** [apache/eventmesh#4502]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Currently in the project, most places determine whether to print logs through conditional checks. Now there is a common utility class LogUtils to handle these conditional checks. This makes the code look much simpler.

### current situation
![image](https://github.com/apache/eventmesh/assets/15797831/83a181df-36b1-4d8f-ba37-4d6095d3f093)

### After settlement
![image](https://github.com/apache/eventmesh/assets/15797831/8bb5d24e-01c9-43df-9c39-ec4a2cbf8058)

**Note: Developers need to judge whether each place needs to be changed. For example, some prints are mandatory and do not need conditional checks, so there is no need to change them.**

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by scwlkq** [comment]
i will try this

**Comment by Pil0tXia** [comment]
@scwlkq Welcome to EventMesh community, my friend!

**Comment by mxsm** [comment]
@scwlkq Welcome to EventMesh community!

**Comment by luahan77m** [comment]
Hi, I'm new to open source and want to try to solve some simple problems. Can you assign this issue to me? I would appreciate it!

**Comment by scwlkq** [comment]
> Hi, I'm new to open source and want to try to solve some simple problems. Can you assign this issue to me? I would appreciate it!

Hello, I am also a newcomer to the community. I have previously claimed this task. In fact, I have already written about it, and the code volume is a bit large.
