### ISSUE TITLE
[Unit Test] Unit test for ThreadUtils

### ISSUE THREAD

**Issue by harshithasudhakar** [apache/eventmesh#4540]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

Add Unit Test for ThreadUtils.java

### Describe the unit tests you want to do

Module name: eventmesh-common
Located at: [eventmesh](https://github.com/apache/eventmesh/tree/master)/[eventmesh-common](https://github.com/apache/eventmesh/tree/master/eventmesh-common)/[src](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src)/[main](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main)/[java](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java)/[org](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org)/[apache](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache)/[eventmesh](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache/eventmesh)/[common](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache/eventmesh/common)/[utils](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache/eventmesh/common/utils)/[ThreadUtils.java](https://github.com/apache/eventmesh/blob/master/eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/ThreadUtils.java)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by harshithasudhakar** [comment]
@VishalMCF yeah, I'm working on it.

**Comment by melisolmez** [comment]
Hello, I want to work on this isuue. Could I take on this task and contribute?

**Comment by harshithasudhakar** [comment]
Sure, please go ahead :)

**Comment by melisolmez** [comment]
Hİ, @harshithasudhakar, Could you review my pr please
