### ISSUE TITLE
[Unit Test] Add unit test for OpenFunctionSourceConnector.

### ISSUE THREAD

**Issue by yanrongzhen** [apache/eventmesh#4547]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

Add unit test for OpenFunctionSourceConnector.

### Describe the unit tests you want to do

Add unit test for OpenFunctionSourceConnector.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by VishalMCF** [comment]
@yanrongzhen I can take this up. I have finished the exploration and will raise the PR soon.
