### ISSUE TITLE
[Unit Test] Add unit test for OpenFunctionSinkConnector.

### ISSUE THREAD

**Issue by yanrongzhen** [apache/eventmesh#4548]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

Add unit test for OpenFunctionSinkConnector.

### Describe the unit tests you want to do

Add unit test for OpenFunctionSinkConnector.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by VishalMCF** [comment]
@yanrongzhen Can I start working on this issue, I can see you have not mentioned submitting a PR.

**Comment by yanrongzhen** [comment]
> @yanrongzhen Can I start working on this issue, I can see you have not mentioned submitting a PR.

Of course. Welcome to the EventMesh community!

**Comment by VishalMCF** [comment]
Hello @yanrongzhen I found the implementation of the test for the RedisSinkConnector. There I found the methodology for unit testing a Sink Connector which can be summarised as follows:-
1. Create an instance of SinkConnector
2. Extract the storage part (in case of RedisSinkConnector it is RTopic but in case of OpenFunction it will become its BlockingQueue)
3. Start the connector
4. Create multiple objects of ConnectorRecords and put it inside the storage of the SinkConnector. 
5. Add a listener to the storage that can consume the events/records from it and that should match as exactly the ones which were put inside the storage. 
But in case of RedisSinkConnector we are able to test it by using a mock Redis Server. How can I do the same in case of OpenFunction? I really like this issue as it is teaching me a lot of concepts. Hope you can provide some guidance. :)

**Comment by yanrongzhen** [comment]
Hello @VishalMCF , I think you can refer to ‘SpringSinkConnector’, and the steps should be similar.

**Comment by VishalMCF** [comment]
@yanrongzhen I guess I have yet to explore that.  Thanks a lot lol

**Comment by VishalMCF** [comment]
@yanrongzhen I can take this up now. I have finished the exploration and will raise the PR soon.

**Comment by yanrongzhen** [comment]
@VishalMCF Welcome to contribute!

**Comment by VishalMCF** [comment]
@yanrongzhen Please assign this to me. I can work on it now.
