### ISSUE TITLE
[Enhancement]  The logical operations in prehandler and posthandler are not reasonable

### ISSUE THREAD

**Issue by lrhkobe** [apache/eventmesh#4551]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Time-consuming statistics are more reasonable in posthandler.

Code in `HandlerService.java`:
[
![企业微信截图_16995834577905](https://github.com/apache/eventmesh/assets/34571087/eb13bba6-6791-4953-bd8e-41e77de5fccd)
](url)

Code in the method of `preHandler`:
```
       private void preHandler() {
            metrics.getSummaryMetrics().recordHTTPReqResTimeCost(System.currentTimeMillis() - requestTime);
            LogUtils.debug(httpLogger, "{}", response);
        }
```

### Describe the solution you'd like

Optimize the logic in prehandler and posthandler.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by cnzakii** [comment]
I would like to try it, please assign me.
Clarify my task: move `metrics.getSummaryMetrics().recordHTTPReqResTimeCost(System.currentTimeMillis() - requestTime);` in the method of `preHandler` to the last line in the method of `postHandler`.

**Comment by Pil0tXia** [comment]
@cnzakii 

Including logger and any time-consuming statistics method.

It's better to finish multiple PRs one by one.

**Comment by cnzakii** [comment]
OK. I will come back to claim the issue after submitting the previous PR (if the issue still exists)

**Comment by cnzakii** [comment]
@Pil0tXia 

I've already submitted the previous PR, so I think I can apply to address this issue now.

My solution:
![2024-04-09_19 57 54](https://github.com/apache/eventmesh/assets/91261012/e9fcc0f5-009d-4863-b45b-dca660159025)

As shown in the diagram above, move the code from the `preHandler` method to the `postHandler` method.

**Comment by Pil0tXia** [comment]
@cnzakii 

As you can see that there are also some metrics related statements in `postHandler()`, so better put them at the top of the `postHandler()`.

**Comment by cnzakii** [comment]
@Pil0tXia 

OK. But I noticed that `preHandler()` is only used within `run()`, whereas `postHandler()` is used not only in `run()` but also in the `sendResponse()` method. If we move the `preHandler()` code into `postHandler()`, will it not add some unnecessary logging and time-consuming statistics?

![2024-04-09_20 45 46](https://github.com/apache/eventmesh/assets/91261012/a370508b-11e5-4145-8b4d-50df70bf7995)

**Comment by Pil0tXia** [comment]
The time-consuming statistics in `postHandler()` is acceptable, however the time `recordHTTPReqResTimeCost()` method recorded will be a little incorrect. Maybe creating another method and renaming these two methods if necessary will be a better way to resolve this issue.

**Comment by cnzakii** [comment]
@Pil0tXia 

Could you further explain your thoughts to me? I'm not quite understanding.

Another idea I had is simply to rearrange the position of the `preHandler()` method.

![2024-04-09_23 12 23](https://github.com/apache/eventmesh/assets/91261012/25d560ff-8429-4d84-8cd9-4cca63bd80a8)

**Comment by Pil0tXia** [comment]
You may wrap one method to another and call different methods under certain circumstances.

**Comment by cnzakii** [comment]
> @cnzakii You may wrap one method to another and call different methods under certain circumstances.

@Pil0tXia 

Is it similar to the concept of the wrapper pattern, where we create a wrapper method for `postHandler()`, which would perform the tasks of `preHandler()` within this method before calling `postHandler()`?

**Comment by Pil0tXia** [comment]
@cnzakii yeah

**Comment by cnzakii** [comment]
@Pil0tXia 

OK. Please assign the issue to me. By the way, do you have any good suggestions for naming methods?

**Comment by Pil0tXia** [comment]
@Pil0tXia You can exert your abilities and make your own decisions. After you submit a PR, I will review it again.

**Comment by cnzakii** [comment]
@Pil0tXia PTAL
