### ISSUE TITLE
[Question] Why does the connector need two init methods?

### ISSUE THREAD

**Issue by hhuang1231** [apache/eventmesh#4565]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

![image](https://github.com/apache/eventmesh/assets/122422744/5e263559-6a91-4ac9-b133-d46bf0764fce)

In the `org.apache.eventmesh.openconnect.SinkWorker#init()`, just call `org.apache.eventmesh.openconnect.api.connector.Connector#init(org.apache.eventmesh.openconnect.api.connector.ConnectorContext )`(the second method framed below), then what is the role of the first method in the picture below.

---
在`org.apache.eventmesh.openconnect.SinkWorker#init()`方法中，只会调用`org.apache.eventmesh.openconnect.api.connector.Connector#init(org.apache.eventmesh.openconnect.api.connector.ConnectorContext)`接口方法（如下图中框起来的第二个方法），那么下图中第一个方法是有什么作用。

![image](https://github.com/apache/eventmesh/assets/122422744/7e0a1791-a8ba-4e68-8b58-16fb72742a4f)

**Comment by mxsm** [comment]
@hhuang1231 At the beginning, there was only the first initialization method. However, as many connectors were developed, the ConnectorContext was later introduced. In my opinion, the second method was added for compatibility reasons. I suggest marking the first one as deprecated, and it could be removed in future versions. The current version can still maintain both methods.

**Comment by xwm1992** [comment]
> @hhuang1231 At the beginning, there was only the first initialization method. However, as many connectors were developed, the ConnectorContext was later introduced. In my opinion, the second method was added for compatibility reasons. I suggest marking the first one as deprecated, and it could be removed in future versions. The current version can still maintain both methods.

Yes, your statement is correct.

**Comment by mxsm** [comment]
This qustion issue will be closed
