### ISSUE TITLE
[Unit Test] Unit test based on redis-mock occasionally fails in CI

### ISSUE THREAD

**Issue by pandaapo** [apache/eventmesh#4566]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

During CI execution, the unit test based on redis-mock occasionally fails here. It has occurred several times.

CI执行的时候，基于redis-mock的单元测试在这里偶尔会失败。已出现数次。
https://github.com/apache/eventmesh/blob/715423c68ff3df1c3a065080c4ffd6707efe891e/eventmesh-storage-plugin/eventmesh-storage-redis/src/test/java/org/apache/eventmesh/storage/redis/connector/UnitTest.java#L107
```
> Task :eventmesh-storage-plugin:eventmesh-storage-redis:test

UnitTest > testPubSub() FAILED
    org.opentest4j.AssertionFailedError at UnitTest.java:107

6 tests completed, 1 failed

> Task :eventmesh-storage-plugin:eventmesh-storage-redis:test FAILED
```

### Describe the unit tests you want to do

Find the cause of the failure.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scwlkq** [comment]
I will try to fix it.

**Comment by scwlkq** [comment]
问题代码行在issue之后进行过更改，问题似乎已经解决
![image](https://github.com/apache/eventmesh/assets/89067331/67a11dcb-8e6f-4f59-8998-05eb29b41f76)
![image](https://github.com/apache/eventmesh/assets/89067331/2dadb299-1d83-4eb5-8d34-424c081e8a09)
