### ISSUE TITLE
[Question] How to elegantly use the extension field in ConnectRecord to sink messages?

### ISSUE THREAD

**Issue by hhuang1231** [apache/eventmesh#4567]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

Currently I try to use connector-spring's soouce to send messages and then sink in DingTalk.

目前我尝试使用connector-spring的soouce来发送消息，然后在钉钉中下沉。
- Since DingTalk requires special extension fields, I first need to add `org.apache.eventmesh.connector.spring.source.connector.SpringSourceConnector#send(java.lang.Object, org.apache.eventmesh.openconnect.api. callback.SendMessageCallback)` method, add the required extension fields to `ConnectRecord`

   由于钉钉需要特殊的扩展字段，所以我首先需要在`org.apache.eventmesh.connector.spring.source.connector.SpringSourceConnector#send(java.lang.Object, org.apache.eventmesh.openconnect.api.callback.SendMessageCallback)`方法，将需要的扩展字段添加进`ConnectRecord`中

- And due to CloudEvent's [name conventions](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#naming-conventions), I also have to convert the `dingdingtemplatetypekey` to all lowercase before I can put it into the `extension` of `CloudEvent`

  并且由于CloudEvent的[命名约束](https://github.com/cloudevents/spec/blob/main/cloudevents/languages/zh-CN/spec.md#naming-convention%E5%91%BD%E5%90%8D%E7%BA%A6%E5%AE%9A)，我也必须将`dingdingtemplatetypekey`转为全部小写，才能将其放入`CloudEvent`的`extension`中

  ![image](https://github.com/apache/eventmesh/assets/122422744/af99060f-855c-44b8-885f-b0fd034c7bd7)

- And had to modify the source code of `org.apache.eventmesh.openconnect.SourceWorker#convertRecordToEvent` so that it can get `extension` from `ConnectRecord` and add it to `CloudEvent`

  并且不得不修改`org.apache.eventmesh.openconnect.SourceWorker#convertRecordToEvent`的源代码使其可以从`ConnectRecord`中得到`extension`并添加到`CloudEvent`中
 
  ![image](https://github.com/apache/eventmesh/assets/122422744/2ecaa485-0027-401a-ba97-5ec29e12e450)

    - In addition, I found that sinkWoker will call `org.apache.eventmesh.openconnect.util.CloudEventUtil#convertEventToRecord` when receiving events, thereby completing the conversion from `CloudEvent`'s `extension` to `ConnectorRecord`'s `extension`, and sourceWoker But they didn't do this. Why?
    
      另外我发现sinkWoker接收事件的过程中将会调用`org.apache.eventmesh.openconnect.util.CloudEventUtil#convertEventToRecord`，从而完成从`CloudEvent`的`extension`转换为`ConnectorRecord`的`extension`，而sourceWoker却没有这么做，这是为什么呢？
 
        ![image](https://github.com/apache/eventmesh/assets/122422744/458a91ca-86f7-48ef-bce6-7c438ed64f6d)

My doubts should be similar to #4560, and I hope to understand the community's current plans for this area.

我的疑惑与#4560 应该是类似的，我希望能够了解社区目前对于这一块的计划。

**Comment by xwm1992** [comment]
SourceWorker是由connectorRecord转为cloudevents协议，再发给EventMesh；SinkWorker是由cloudevents转为connectorRecord再调用connect api. 因此connect api部分都是connectorRecord，与eventmesh交互部分都是cloudevents.

**Comment by hhuang1231** [comment]
@xwm1992 假如我想在应用程序中直接调用eventmesh提供的api来发送事件到mesh，目前我只知道两种方式：
1. 利用原生的java sdk在应用程序中new connectorRecord后，再发送给mesh，mesh再根据topic发送给sink。
2. 利用connector-spring的source来发送。_特别地，它提供的send方法将ConnectRecord隐藏了起来，那么用户将无法为其添加额外的extension。这样将无法满足将消息发送到钉钉那种需要特殊字段标识的sink中的条件_。

我主要想知道如果想让用户使用更方便的话，是不是应该对在应用程序中发送ConnectRecord做更多的优化，例如丰富spring的支持。
除此之外我还想知道目前connector中的spring和#2314 中提到的利用spring简化java sdk的使用有什么区别。

**Comment by xwm1992** [comment]
> @xwm1992 假如我想在应用程序中直接调用eventmesh提供的api来发送事件到mesh，目前我只知道两种方式：
> 
> 1. 利用原生的java sdk在应用程序中new CloudEvent后，再发送给mesh，mesh再根据topic发送给sink。
> 2. 利用connector-spring的source来发送。_特别地，它提供的send方法将ConnectRecord隐藏了起来，那么用户将无法为其添加额外的extension。这样将无法满足将消息发送到钉钉那种需要特殊字段标识的sink中的条件_。
> 
> 我主要想知道如果想让用户使用更方便的话，是不是应该对在应用程序中发送CloudEvent做更多的优化，例如丰富spring的支持。 除此之外我还想知道目前connector中的spring和#2314 中提到的利用spring简化java sdk的使用有什么区别。

1. 首先通过api调用来发送事件到mesh的两种方式描述的不是很对，一种是通过sdk的方式，另外一种是采用restful api的方式；你说的connector-spring，这个只是connector集成了eventmesh的sdk来进行了封装，任何一种connector都是集成了eventmesh sdk，无非spring是直接面向应用程序的，这个点正是我们想要体现的，让用户看到的是spring的方式，至于 #2314中提到的和 @pandaapo 回复的内容是一致的，因为mesh原本是netty server实现的，该issue讨论的是是否用spring的方式来实现mesh。
2. 对于你说的spring connector和dingding connector无法很好的配合使用这个点，我理解主要问题点在于spring connector现有的source设计是直接将json化后的message作为event发给了mesh，并没有考虑相关的扩展字段的问题，这个点是可以考虑进行优化的，这个问题背景是spring connector是先提交实现的，没有考虑到和其他connector结合的问题，因此没有保留扩展属性。
@yanrongzhen 也可以看一下这里的讨论，看看你的想法。

**Comment by yanrongzhen** [comment]
> > @xwm1992 假如我想在应用程序中直接调用eventmesh提供的api来发送事件到mesh，目前我只知道两种方式：
> > 
> > 1. 利用原生的java sdk在应用程序中new CloudEvent后，再发送给mesh，mesh再根据topic发送给sink。
> > 2. 利用connector-spring的source来发送。_特别地，它提供的send方法将ConnectRecord隐藏了起来，那么用户将无法为其添加额外的extension。这样将无法满足将消息发送到钉钉那种需要特殊字段标识的sink中的条件_。
> > 
> > 我主要想知道如果想让用户使用更方便的话，是不是应该对在应用程序中发送CloudEvent做更多的优化，例如丰富spring的支持。 除此之外我还想知道目前connector中的spring和#2314 中提到的利用spring简化java sdk的使用有什么区别。
> 
> 1. 首先通过api调用来发送事件到mesh的两种方式描述的不是很对，一种是通过sdk的方式，另外一种是采用restful api的方式；你说的connector-spring，这个只是connector集成了eventmesh的sdk来进行了封装，任何一种connector都是集成了eventmesh sdk，无非spring是直接面向应用程序的，这个点正是我们想要体现的，让用户看到的是spring的方式，至于 #2314中提到的和 @pandaapo 回复的内容是一致的，因为mesh原本是netty server实现的，该issue讨论的是是否用spring的方式来实现mesh。
> 2. 对于你说的spring connector和dingding connector无法很好的配合使用这个点，我理解主要问题点在于spring connector现有的source设计是直接将json化后的message作为event发给了mesh，并没有考虑相关的扩展字段的问题，这个点是可以考虑进行优化的，这个问题背景是spring connector是先提交实现的，没有考虑到和其他connector结合的问题，因此没有保留扩展属性。
>    @yanrongzhen 也可以看一下这里的讨论，看看你的想法。

我个人觉得spring可能需要支持extension, 一般使用spring的用户, 配置都在spring的environment里, 我觉得可以把spring environment和connector做一个联动.

**Comment by hhuang1231** [comment]
@pandaapo @yanrongzhen 
1. 为什么不让key=value中的key更加清晰简单一点呢，例如使用模块名dingtalk代替dingtalkTemplateType，这有什么不妥吗？
2. 在eventmesh-connector-wecom模块中也有类似的问题，可能需要解决

**Comment by hhuang1231** [comment]
> @pandaapo @yanrongzhen
> 
> 1. 为什么不让key=value中的key更加清晰简单一点呢，例如使用模块名dingtalk代替dingtalkTemplateType，这有什么不妥吗？
> 2. 在eventmesh-connector-wecom模块中也有类似的问题，可能需要解决。并且在`org.apache.eventmesh.connector.wecom.constants.ConnectRecordExtensionKeys`的定义中，由于出现了`:`，这将无法正常写入properties文件中作为key

**Comment by xwm1992** [comment]
> > 通过api调用来发送事件到mesh的两种方式……，一种是通过sdk的方式，另外一种是采用restful api的方式；
> 
> @xwm1992 restful api的方式我不是很确定，是指像这个issue中“Management Interface in EventMesh”部分描述的方式吗 [#4400 (comment)](https://github.com/apache/eventmesh/issues/4400#issue-1864925831) ？如果是的，是不是还在完善和补充中？

目前EventMesh 的http调用是有两种方式，一种是sdk，另外一种是直接调用eventmesh的uri，你可以看对应http协议下面的processor与uri之间的映射关系
