### ISSUE TITLE
[Enhancement] There is no metaStorage plugin of type "namesrv"

### ISSUE THREAD

**Issue by pandaapo** [apache/eventmesh#4584]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

https://github.com/apache/eventmesh/blob/4e72b3c8c5f0434ffa144a2a364361d93582fcf0/eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java#L62

There is no metaStorage plugin of type "namesrv".

### Describe the solution you'd like

Remove it or change it to "nacos".

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by VishalMCF** [comment]
@pandaapo I will take this up.
