### ISSUE TITLE
[Question] After crashing the runtime and restarting it, the grpc client will not be able to reconnect by sending heartbeat packets.

### ISSUE THREAD

**Issue by hhuang1231** [apache/eventmesh#4587]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

The connection between the client and the runtime can be maintained through heartbeat detection. For http and tcp, when the runtime crashes and then restarts, the connection can be reacquired through the heartbeat packet, but for grcp, once the runtime crashes, `io.grpc.stub.StreamObserver` will be marked as completed. At this time, the client will no longer be able to send heartbeat packets, and will not be able to reconnect to the runtime.

Please tell me if this is a bug?

---
通过心跳检测可以保持client与runtime的连接。对于http和tcp来说，当runtime宕机再重启后，通过心跳包可以重新获取连接，但是对于grcp来说，一旦runtime宕机就会标记`io.grpc.stub.StreamObserver`为completed。此时client将无法再发送心跳包，进而无法重新连接runtime。

请问这是否是个bug？

![image](https://github.com/apache/eventmesh/assets/122422744/596def9a-a0bc-4c68-a6cc-5f4ed7976917)

![image](https://github.com/apache/eventmesh/assets/122422744/71c95c58-ca59-4299-8bbb-4484c062d4e5)
![image](https://github.com/apache/eventmesh/assets/122422744/22424bb2-94bf-4c24-bcc3-a9944575720b)

**Comment by hhuang1231** [comment]
I also want to know why `org.apache.eventmesh.client.grpc.consumer.EventMeshGrpcConsumer#resubscribe` is limited to using subStreamHandler for sending.
我还想知道`org.apache.eventmesh.client.grpc.consumer.EventMeshGrpcConsumer#resubscribe`为什么限定使用subStreamHandler进行发送。


![image](https://github.com/apache/eventmesh/assets/122422744/009d6118-b8ca-4d18-a14d-234a69f3797a)
As far as I know, there are only two ways to create a subStreamHandler:
1. Call `public void subscribe(final List<SubscriptionItem> subscriptionItems)` to automatically create
2. Call the setter
For the startup method of grpc springboot in examples, subStreamHandler is not created, so NPE will be thrown when resubscribe is called.

我目前所知创建subStreamHandler应该只有两种方式：
1. 调用`public void subscribe(final List<SubscriptionItem> subscriptionItems)`自动创建
2. 调用setter

而对于examples中grpc springboot的启动方式来说，并没有创建subStreamHandler，因此当调用resubscribe时将会抛出NPE

**Comment by mxsm** [comment]
This issue has been resolved through the corresponding pull request and will be closed.
