### ISSUE TITLE
Load connector

### ISSUE THREAD

**Issue by brampurnot** [apache/eventmesh#4600]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

Hi all!

I'm still pretty new and learning here. I just got a basic question. I managed to set up the eventmesh locally and in a Kubernetes cluster as well. 

Next thing I'm learning is to use a sink connector (mongo or slack). However they don't seem to be loading. The /conf/server-config.yaml has the following defined:
sinkEnable: true

And I also configured the sink-config.yaml file. But it doesn't seem to be loading anything. Is there anything additional I need to do? I went through the documentation but it's very poor when it comes to using connectors.

Any help is appreciated!

Bram

**Comment by fabian4** [comment]
@pandaapo Yes, we have the same one in the example project right now.

**Comment by brampurnot** [comment]
Thanks for the info both. That helps a lot. We didn't start the connector since we believed it was loaded on the fly when starting event mesh but now we get. We will give that a try. 

Is there some kind of fat JAR generated when doing a gradle build or do we have to do that ourselves? 

Bram

**Comment by brampurnot** [comment]
Gotcha! That clarifies a lot. Thanks both for the swift response.

Bram

**Comment by fabian4** [comment]
@pandaapo The config file here: https://github.com/apache/eventmesh/tree/master/eventmesh-connectors/eventmesh-connector-mongodb/src/main/resources
Sorry for the misleading.
