### ISSUE TITLE
[Bug]requests lost

### ISSUE THREAD

**Issue by zscomehuyue** [apache/eventmesh#4630]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux

### EventMesh version

master

### What happened

The server core thread pool of Mesh adopts a default dropout strategy; Assuming there is blocking, important requests will be lost;

### How to reproduce

The connection between MESH and Rocketmq is disconnected, and the client sends a large number of messages;

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by xwm1992** [comment]
I think the situation you gave is a message sending failure, not a message loss, because the connection between the mesh and the broker is disconnected, which has nothing to do with the dropout strategy of the thread pool.

---
我认为你举例这种情况属于消息发送失败，并不是消息丢失，因为mesh与broker的连接断开，与线程池的dropout策略没有关系

**Comment by zscomehuyue** [comment]
当我发送过快消息时，服务端队列1w，会超过该队列时，会触发丢弃策略，EventMeshTcpExceptionHandler的异常处理会触发close session；客户端会进行重新连接；
而被关闭的有可能是订阅session，也有可能是发送session；
感觉服务端丢弃也是合理的，过多的消息，服务端不能及时处理，只有丢弃（放到本地线程执行会影响整体性能）

**Comment by zscomehuyue** [comment]
当我发送过快消息时，服务端队列1w，会超过该队列时，会触发丢弃策略，EventMeshTcpExceptionHandler的异常处理会触发close session；客户端会进行重新连接；
而被关闭的有可能是订阅session，也有可能是发送session；
感觉服务端丢弃也是合理的，过多的消息，服务端不能及时处理，只有丢弃（放到本地线程执行会影响整体性能）
