### ISSUE TITLE
[Enhancement] Optimize the message body of the Rust SDK's returned reply message

### ISSUE THREAD

**Issue by mxsm** [apache/eventmesh#4633]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Optimize the message body of the Rust SDK's returned reply message.
link #4631 

### Describe the solution you'd like

Optimize the message body of the Rust SDK's returned reply message

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by kyooosukedn** [comment]
Hi, I am willing to work on this issue, can u please provide more details? I looked into request_reply_inner method inside grpc_client.rs and AFAIK what i need to do is 
1. Check if it's a subscription reply message
2. Do additional logging for subscription reply
3. Add attributes to indicate subscription response

**Comment by mxsm** [comment]
> Hi, I am willing to work on this issue, can u please provide more details? I looked into request_reply_inner method inside grpc_client.rs and AFAIK what i need to do is
> 
> 1. Check if it's a subscription reply message
> 2. Do additional logging for subscription reply
> 3. Add attributes to indicate subscription response

@kyooosukedn Sure.
Delete the SubscriptionReply struct, which has already been deleted in the Java SDK. For more details, please refer to PR#4632. For the specific implementation logic, please refer to the Java SDK SubStreamHandler#createReceiver method.
The implementation in the Rust SDK is in the subscribe method in grpc_consumer.rs. Here you can find that only EventMeshMessage is supported, and other modifications will be made later. Therefore, you can simply follow the existing logic.
![image](https://github.com/apache/eventmesh/assets/15797831/ed1e3b16-dd3f-4f3b-9377-23915bf94089)
