### ISSUE TITLE
[Bug] HTTP source connector stop after receiving an invalid request

### ISSUE THREAD

**Issue by Fungx** [apache/eventmesh#4659]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux

### EventMesh version

master

### What happened

 HTTP source connector stop after receiving an request without attribute `subject` and never response again.

### Reproduce
1. start http connector server
2. send an invalid request without `subject`, such as 
```shell
curl --location --request POST 'http://localhost:3755/test' \
--header 'ce-id: 11' \
--header 'ce-specversion: 1.0' \
--header 'ce-type: com.example.someevent' \
--header 'ce-source: /mycontext' \
# --header 'ce-subject: test' \
--header 'Content-Type: text/plain' \
--data-raw 'aaa'
```
3. http connector server stop forever

### Analysis 
In `HttpSourceConnector#poll`, the conversion from cloudevent to connectRecord is performed.
![image](https://github.com/apache/eventmesh/assets/38498093/a02c4add-297c-4b3f-8651-f3b2bd31ae7d)

If a cloudevent contains null `subject`, `connectRecord.addExtension("topic", event.getSubject())` will throw unexpected NPE, which will stop the connector server.
![image](https://github.com/apache/eventmesh/assets/38498093/a5c1c4ad-5980-45ba-a192-2496367df907)

### Fix
Check `subject` before saving cloudevents. We don't need to check other attributes like `id`, `source`, `type`,etc. Because they are required arrtibutes of cloudevents and cloudevents-sdk will do the check in `toEvent()`. 
```java
VertxMessageFactory.createReader(ctx.request())
                    .map(r -> {
                        CloudEvent event = r.toEvent();
                        if (event.getSubject() == null) {
                            throw new IllegalStateException("attribute 'subject' cannot be null");
                        }
                        return event;
                    })
setting others...
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by Pil0tXia** [comment]
Good. Is there a way for the sender to get that there is an error in one of the packets sent without looking at the EM logs?

**Comment by Fungx** [comment]
> Good. Is there a way for the sender to get that there is an error in one of the packets sent without looking at the EM logs?

Sender can get it from the http status code.  `400` will be returned if there is an error in the conversion.
