### ISSUE TITLE
Coceptual Question:- Doubts regarding Connector Source, Connector Sink, Storage and Eventmesh Runtime.

### ISSUE THREAD

**Issue by VishalMCF** [apache/eventmesh#4680]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

Will add the details soon.

**Comment by VishalMCF** [comment]
![image](https://github.com/apache/eventmesh/assets/70262922/74ee1274-b4ec-49ea-8fd4-193d91fc9826)

**Comment by Pil0tXia** [comment]
1. `eventmesh-storage-rocketmq` has been loaded by default in `eventmesh-runtime/build.gradle#L43`
2. Connectors can be deployed on any machine, including the machine which has started EventMesh Runtime already.
3. It is planned to integrate Connectors into K8s.
4. EventMesh supports the architecture you have provided. You will need to deploy the MongoDB source connector, the Spring sink connector, and integrate the `eventmesh-storage-pulsar` dependency into the EventMesh Runtime plugin binary file.

**Comment by VishalMCF** [comment]
@Pil0tXia Please read the comment again as I was in the middle of editing it.

**Comment by Pil0tXia** [comment]
Here is my response to the part you added:

1. The documentation for the Spring connector is still being improved, and you can expect to see usage instructions as early as next month. If you prefer not to use the connector, you can utilize the EventMesh SDK in your application. Please refer to the following link for more information: [EventMesh SDK for Java](https://eventmesh.apache.org/docs/next/sdk-java/intro).
2. There is no need to deploy Pulsar connector.

**Comment by VishalMCF** [comment]
Great! Thanks for your quick help. @Pil0tXia

**Comment by VishalMCF** [comment]
@pandaapo Please check here:-
https://eventmesh.apache.org/docs/instruction/runtime#113-build-and-load-plugins
