### ISSUE TITLE
[Enhancement] Incorrect line numbers displayed for LogUtils when printing logs

### ISSUE THREAD

**Issue by Pil0tXia** [apache/eventmesh#4681]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/41445332/adfd28b9-5d30-4b03-89bf-c13327a24256)

### Describe the solution you'd like

Related PR: https://github.com/apache/eventmesh/pull/4507

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by scwlkq** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.
> 
> ### Enhancement Request
> ![image](https://private-user-images.githubusercontent.com/41445332/291573048-adfd28b9-5d30-4b03-89bf-c13327a24256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODYwOTcsIm5iZiI6MTcwMjk4NTc5NywicGF0aCI6Ii80MTQ0NTMzMi8yOTE1NzMwNDgtYWRmZDI4YjktNWQzMC00YjAzLTg5YmYtYzEzMzI3YTI0MjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDExMzYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZGE0MmM2ZDc3ZjczMDRhMzYyOWRkMTQzZmFmZDE4NGMyYjI3MWZhNTA0OTY1MjMyMjA1ZDBlMzhkMDc0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8sh-Xoi-NsVeMmpzSg-xrlbiyjrwP8ww979LOWPdFJ8)
> 
> ### Describe the solution you'd like
> Related PR: #4507 Assigned to @scwlkq
> 
> ### Are you willing to submit PR?
> * [x]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh/pull/4698
