### ISSUE TITLE
[Enhancement] Substitute `e.printStackTrace()` with `log.error()`

### ISSUE THREAD

**Issue by Pil0tXia** [apache/eventmesh#4733]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/41445332/f55c5d88-5631-4c9c-a33d-63588e44a34c)

`e.printStackTrace()` should be substituted with `log.error()` in these classes:

- org.apache.eventmesh.runtime.client.impl.PubClientImpl
- org.apache.eventmesh.openconnect.SourceWorker
- org.apache.eventmesh.common.ThreadWrapperTest

### Describe the solution you'd like

Take `org.apache.eventmesh.runtime.client.impl.PubClientImpl` as an example:

![image](https://github.com/apache/eventmesh/assets/41445332/714522a3-c3ac-48ec-8c7c-52b59f75f5bc)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by MovieTone** [comment]
Hi @Pil0tXia, I can fix this enhancement issue as well, would be happy to be assigned

**Comment by Pil0tXia** [comment]
@MovieTone How about temporarily leaving this issue to someone else who is interested in contributing to open source?

**Comment by MovieTone** [comment]
@Pil0tXia Yes, sure

**Comment by ppkarwasz** [comment]
@Pil0tXia,

There is an OpenRewrite recipe for this: https://docs.openrewrite.org/recipes/java/logging/printstacktracetologerror

You can also run it regularly to convert new call sites of `Throwable#printStackTrace()` (some IDEs, such as Eclipse add it as default `catch` content).

**Comment by Pil0tXia** [comment]
@ppkarwasz Hah, I remember that. There are only three remaining usages of printStackTrace(), which can be resolved in a good first issue.😉

**Comment by archit-8** [comment]
Hi @Pil0tXia, can  you assign me this  enhancement issue.

**Comment by Pil0tXia** [comment]
@archit-8 Welcome to Apache EventMesh community!

**Comment by archit-8** [comment]
thanks, hey can  you share  path of a  files where changes   are going to  happen.

**Comment by Pil0tXia** [comment]
@archit-8 

> share path of a files where changes are going to happen.

They are listed in the body of the issue:

![image](https://github.com/apache/eventmesh/assets/41445332/e6463989-04bf-4497-b18b-9152071a003f)

**Comment by archit-8** [comment]
1.org.apache.eventmesh.runtime.client.impl.PubClientImpl 
   not able to relocate this class in a project

2.org.apache.eventmesh.openconnect.SourceWorker
changes are made successfully and merged

3.org.apache.eventmesh.common.ThreadWrapperTest
no changes

thanks for  help

**Comment by mxsm** [comment]
@Pil0tXia This issue has finished?

**Comment by Pil0tXia** [comment]
@mxsm Not yet. The assignee haven't submit a PR yet.
