### ISSUE TITLE
[Enhancement] Use the `static final` modifier to decorate `Logger`

### ISSUE THREAD

**Issue by Pil0tXia** [apache/eventmesh#4734]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

In Java, it is a best practice to declare a logger static final.

- `private` - so that no other class can hijack your logger
- `static` - so there is only one logger instance per class, also avoiding attempts to serialize loggers
- `final` - no need to change the logger over the lifetime of the class

Location:

Search for `private final Logger` in project source code.

### Describe the solution you'd like

Add `static` modifier for `Logger`, rename `foobarLogger` to `FOOBAR_LOGGER`, and substitute logger name with constants.

Take `org.apache.eventmesh.runtime.metrics.tcp.EventMeshTcpMonitor` as an example:

![image](https://github.com/apache/eventmesh/assets/41445332/10ddcc93-0682-47ff-8417-8ac241d8e014)

You can add more constants in `org.apache.eventmesh.runtime.constants.EventMeshConstants`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by MovieTone** [comment]
Hey @Pil0tXia, would be glad to be assigned to fix this issue!

**Comment by Pil0tXia** [comment]
@MovieTone Welcome to EventMesh community!

**Comment by Pil0tXia** [comment]
@MovieTone If you wish to start coding immediately, you may proceed with further modifications based on https://github.com/apache/eventmesh/pull/4698 to avoid potential conflicts. Alternatively, you can wait until this pull request is merged into the master branch and then code on the master branch.

**Comment by MovieTone** [comment]
@Pil0tXia Thank you! I'll probably wait for the merge then

**Comment by Pil0tXia** [comment]
@MovieTone Hi! #4698 is merged and it's clear for you now.

**Comment by MovieTone** [comment]
@Pil0tXia Hey, thank you for mentioning! I've created a PR to this
