### ISSUE TITLE
[Enhancement] Integrate Runtime admin endpoints with Netty server

### ISSUE THREAD

**Issue by Pil0tXia** [apache/eventmesh#4738]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Endpoints in `org.apache.eventmesh.runtime.admin.handler` need to be integrated with the EventMesh's existing Netty server instead of Sun HttpServer.

### Describe the solution you'd like

Integrate with `org.apache.eventmesh.runtime.core.protocol.http.processor.inf.HttpRequestProcessor` and EventMeshHTTPServer.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by hanshal101** [comment]
Hey @Pil0tXia I can try this, can you give some more info on this issue.

**Comment by Pil0tXia** [comment]
@hanshal101 Welcome. There's an active developer working on this issue (@karsonto). It would be a good idea if you could go and check the other issues mentioned in the pinned issue.

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh/pull/4739 and https://github.com/apache/eventmesh/pull/4768.
