### ISSUE TITLE
[Bug] The released SDK version does not match the documentation

### ISSUE THREAD

**Issue by scwlkq** [apache/eventmesh#4758]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Windows

### EventMesh version

master

### What happened

![image](https://github.com/apache/eventmesh/assets/89067331/93cca1c3-3bf6-4ad3-b9eb-3f2e9c1101e9)
The project can not load EventMesh Java SDK. Then i find the released SDK version does not match the documentation.

Q1:
From 1.0.0-1.9.0, versions in cn and english docs is always 1.4.0:
![image](https://github.com/apache/eventmesh/assets/89067331/c8f60e75-446d-4b80-ac33-d325b46f721a)
![image](https://github.com/apache/eventmesh/assets/89067331/80a325b3-d77d-4143-ab78-929186cfbcb7)

Q2:
![image](https://github.com/apache/eventmesh/assets/89067331/70049fe6-3d8e-43bc-8822-1b2027e96486)
In MvnRepo, versions all end with ‘release’ exclude 1.4.0. Is it a issue or has an ulterior motive?

### How to reproduce

docs address: https://eventmesh.apache.org/docs/v1.9.0/sdk-java/intro
mvn address: https://mvnrepository.com/artifact/org.apache.eventmesh/eventmesh-sdk-java

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by xwm1992** [comment]
1.4.0 is the version determined when it was released before. It is not a bug. The currently officially released versions all have the release suffix.
