### ISSUE TITLE
[Doc] Update copyright year to 2024

### ISSUE THREAD

**Issue by mxsm** [apache/eventmesh#4761]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

![image](https://github.com/apache/eventmesh/assets/15797831/99fe6bdd-6120-4278-a4d0-c5e516540970)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by orol116** [comment]
Can I work on this issue? kindly assign it to me!

**Comment by mxsm** [comment]
> Can I work on this issue? kindly assign it to me!

Sure. Welcome to the Apache EventMesh community!

**Comment by Pil0tXia** [comment]
This issue is duplicate with https://github.com/apache/eventmesh/issues/4718. I will edit https://github.com/apache/eventmesh/issues/4718 after this issue is closed.
