### ISSUE TITLE
[Bug] eventMesh dashboard does not connect to eventmesh registry container

### ISSUE THREAD

**Issue by erfuuan** [apache/eventmesh#4774]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux

### EventMesh version

master

### What happened

hello everyone
i want run the eventmesh container (eventmesh,dashboardl ,namesrv,broker)
when i want to use dashboard i get an error 

![Screenshot from 2024-02-18 00-21-45](https://github.com/apache/eventmesh/assets/36955603/61bfe1cc-e101-42b6-af51-1165d2d26460)
![Screenshot from 2024-02-18 00-21-57](https://github.com/apache/eventmesh/assets/36955603/0d4aa7e2-b2af-44ef-9780-8e8dd989fa21)

### How to reproduce

![Screenshot from 2024-02-18 00-21-45](https://github.com/apache/eventmesh/assets/36955603/004b1508-80e5-4926-a67f-e224d4232b70)
![Screenshot from 2024-02-18 00-21-57](https://github.com/apache/eventmesh/assets/36955603/71385b47-de95-43b4-b2bd-4eeebdd486ae)

### Debug logs

```Java
i search in the internet but i can not find anything
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by Pil0tXia** [comment]
You have the option to deploy both the container and the dashboard on the same machine, and access the dashboard from this machine to observe whether a successful connection to the cluster can be established.

If you wish to view the Registry page, it is necessary to deploy a corresponding registry center for the cluster, such as Nacos and etcd.

**Comment by erfuuan** [comment]
i deploy the containers with this docker compose : 

`version: '3'
services:
  rmqnamesrv:
    image: apache/rocketmq:latest
    command: sh mqnamesrv
    ports:
      - "9876:9876"
    volumes:
      - ./data/namesrv/logs:/root/logs
      - ./data/namesrv/store:/root/store
    container_name: rmqnamesrv
  rmqbroker:
    image: apache/rocketmq:latest
    command: sh mqbroker -c ../conf/broker.conf
    ports:
      - "10911:10911" 
      - "10909:10909"
    volumes:
      - ./data/broker/logs:/root/logs
      - ./data/broker/store:/root/store
    links: 
      - rmqnamesrv:namesrv 
    environment:
      NAMESRV_ADDR: namesrv:9876
    container_name: rmqbroker
  eventmesh:
    image: apache/eventmesh:latest
    ports:
      - "10000:10000"
      - "10105:10105"
      - "10205:10205"
      - "10106:10106"
    volumes:
      - ./data/eventmesh/conf/eventmesh.properties:/data/app/eventmesh/conf/eventmesh.properties
      - ./data/eventmesh/conf/rocketmq-client.properties:/data/app/eventmesh/conf/rocketmq-client.properties
    container_name: eventmesh
  eventmesh-dashboard:
      image: erfuuan/eventmesh-dashboard:latest
      ports:
        - "8080:80"
      container_name: eventmesh-dashboard

networks:
  eventmesh:
    name: eventmesh
    external: true
`


i see a eventmesh container with telnet 

![Screenshot from 2024-02-18 12-10-54](https://github.com/apache/eventmesh/assets/36955603/7f2d0bbe-d734-4576-ae1d-324d35eb9b14)

but my dashboard does not wotk

**Comment by Pil0tXia** [comment]
Is there any EventMesh port occupied by other applications? Does the examples work? You may check EventMesh Runtime logs for detailed running status.

**Comment by erfuuan** [comment]
The eventmesh port is not busy
i check the log and is was ok

![Screenshot from 2024-02-18 22-26-44](https://github.com/apache/eventmesh/assets/36955603/8dfa18f3-0c91-43f3-9a09-cb0cadd5741c)

my images vesrion is latest 

Is it possible that the versions of our images are different?

**Comment by Pil0tXia** [comment]
May you please press F12 on the Dashboard page and check which endpoint request failed? You may also execute the same request on Postman to exclude browser issue.

**Comment by erfuuan** [comment]
dashboard  call this route :  
	http://localhost:10106/registry

i call with postman but does not work

**Comment by erfuuan** [comment]
response is 404 : 
![Screenshot from 2024-02-19 12-56-50](https://github.com/apache/eventmesh/assets/36955603/edbe69b2-82f2-45a0-8c44-6dd5df9e9eb9)

**Comment by Pil0tXia** [comment]
Got it. The problem occurred due to the bulk renaming of endpoint addresses in the class `org.apache.eventmesh.runtime.admin.handler.MetaHandler`, while the corresponding modifications were not made in the dashboard frontend code.

![image](https://github.com/apache/eventmesh/assets/41445332/85ad6a6e-023d-45bb-a2b0-4e5c013fc93d)

The correct endpoint is now `/meta` instead of `registry`.

**Comment by Pil0tXia** [comment]
@erfuuan 

Considering the "EventMesh Configuration" is displayed correctly in dashboard, and only the `/registry` endpoint has a 404 error, it seems that the EventMesh Runtime container is accessible, doesn't it?

**Comment by erfuuan** [comment]
yes 

I called the method and it worked correctly. But when I called it with the POST method, it didn't work. Have you been able to fully execute or operate this technology without any issues?

**Comment by Pil0tXia** [comment]
>But when I called it with the POST method

I didn't get it. The `/meta` endpoint supports GET method only.

**Comment by erfuuan** [comment]
can i send you direct email?

**Comment by Pil0tXia** [comment]
>can i send you direct email?

okay

**Comment by Pil0tXia** [comment]
See https://github.com/apache/eventmesh-dashboard/issues/39
