### ISSUE TITLE
[Enhancement] Optimize the condition checking in SourceWorker#startPollAndSend

### ISSUE THREAD

**Issue by mxsm** [apache/eventmesh#4785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/15797831/d9d5f31c-c1e6-49f2-a306-66d991ccf8b4)

### Describe the solution you'd like

Replace  0 with OPStatus.SUCCESS.getCode()

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by ketansahugit** [comment]
Hi, if you are not submitting PR for this, i'd like to do it.

**Comment by harshithasudhakar** [comment]
Hi, please feel free to take it up!

> Hi, if you are not submitting PR for this, i'd like to do it.

**Comment by mxsm** [comment]
> Hi, if you are not submitting PR for this, i'd like to do it.

Sure! I have assigned to you @ketansahugit

**Comment by manojks1999** [comment]
Hi team,

https://github.com/apache/eventmesh/pull/4786

This PR has fix for this issue, pls have a look into it.

Thanks

**Comment by manojks1999** [comment]
Hi @mxsm ,

Can you check this PR https://github.com/apache/eventmesh/pull/4786

**Comment by mxsm** [comment]
@manojks1999 Thanks for you contribution.This one has been assigned. I will wait for two days. If he doesn't submit the PR, I will merge yours.

**Comment by mxsm** [comment]
this issue has fixed. I will closed.
