### ISSUE TITLE
[Enhancement] Migrate from fastjson 1.2.83 to fastjson2

### ISSUE THREAD

**Issue by Pil0tXia** [apache/eventmesh#4814]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

fastjson2 was introduced in https://github.com/apache/eventmesh/pull/4813, it's better than fastjson1 and has backward compatibility.

fastjson1 was last maintained on May 23, 2022 and should be upgraded to a new version promptly.

### Describe the solution you'd like

- Update `build.gradle` files
- Update package name to `fastjson2`
- Update `known-dependencies.txt`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by YarBor** [comment]
@Pil0tXia 
I would like to try to optimize this part,
plz assign to me

**Comment by cnzakii** [comment]
I would like to try it, please assign me

**Comment by Pil0tXia** [comment]
@cnzakii 

`com.alibaba.fastjson2:fastjson2:2.0.48` according to https://github.com/apache/eventmesh/pull/4813/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7.

You may start your work after this PR is merged into master.

**Comment by cnzakii** [comment]
> @cnzakii
> 
> `com.alibaba.fastjson2:fastjson2:2.0.48` according to https://github.com/apache/eventmesh/pull/4813/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7.
> 
> You may start your work after this PR is merged into master.

OK
Clarify my tasks: remove the `fastjson:1.2.83` from `build.gradle` and `known-dependencies.txt`, and add the `fastjson2:2.0.48`

**Comment by Pil0tXia** [comment]
@cnzakii 

Yes. You may check check if all existing fastjson1 usage can be seamlessly migrated to fastjson2.

**Comment by cnzakii** [comment]
@Pil0tXia PTAL

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh/pull/4819

@cnzakii Please use `Fixed` keyword in the PR template the next time
