### ISSUE TITLE
[Feature] Add HTTP Sink Connector

### ISSUE THREAD

**Issue by Pil0tXia** [apache/eventmesh#4824]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Send CloudEvents to a specific URL of a HTTP server (like a SpringBoot application endpoint or more).

Needs to support Webhook payload delivary with a general protocol.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by cnzakii** [comment]
![2024-04-10_20 09 36](https://github.com/apache/eventmesh/assets/91261012/55f7394b-8206-4129-9aac-dc3b0a51ab78)
Is completing the above TODO part? I think I can give it a try. Please assign it to me. Thanks~~

**Comment by cnzakii** [comment]
@Pil0tXia 

I've used OkHttpClient to build an HTTP Sink Connector. 

I have some questions regarding message acknowledgment: 
I currently check the HTTP response status code and whether the response body is empty to ensure message delivery success. Should we establish a response template specifying the expected response codes and messages to confirm whether messages were successfully processed, or to retrieve information about the reasons for processing failure? 

Do you have any recommendations on this?

**Comment by Pil0tXia** [comment]
@cnzakii 

I think an HTTP 200 response is enough to represent that the receiver processed the message correctly.

EventMesh is planning in the future to have statistics on the delivery status of events, when it will be necessary to show the results of Webhook deliveries, including what is returned on the sink side. You may leave an extensible design with comments.

Could you please use vertx which has been used in the HTTP Source Connector? Using the same third-party library improves code reusability and later extensibility, and avoids the problem that the Source Connector may produce faster than the Sink Connector can consume.

**Comment by cnzakii** [comment]
@Pil0tXia 

OK, I will make the modifications based on your suggestions.

**Comment by cnzakii** [comment]
@Pil0tXia 

I have a dependency issue to resolve in the `eventmesh-connector-http` module. The version `io.cloudevents:cloudevents-http-vertx:2.3.0` uses Vert.x version 4.0.0, conflicting with `io.vertx:vertx-web:4.4.6`, causing issues with `vertx.WebClient` functionality.

My current approach is:
- Upgrading `io.cloudevents:cloudevents-http-vertx` from 2.3.0 to 3.0.0.
- Downgrading `io.vertx:vertx-web` from 4.4.6 to 4.3.7.

This is because the latest version of `io.cloudevents:cloudevents-http-vertx` available is 3.0.0, which uses Vert.x version 4.3.7.

**Comment by Pil0tXia** [comment]
@cnzakii 

This is the current version in master branch:

https://github.com/apache/eventmesh/blob/fe2bd7c840c9900ad7143099d89a1cc1905a9a09/eventmesh-connectors/eventmesh-connector-http/build.gradle#L21-L22

>The version `io.cloudevents:cloudevents-http-vertx:2.3.0` uses Vert.x version 4.0.0, conflicting with `io.vertx:vertx-web:4.4.6`

For the same artifact, Gradle automatically uses the latest version in the dependency tree. If the old version is **completely unupgradeable** (which is important because upgrading a version is almost always better than downgrading), you can exclude transitive dependencies from conflicting artifacts.

When upgrading, read the release note to avoid unintentionally breaking the functionality of the original code.

My understanding of the situation you described is this:

- While the existing `io.vertx:vertx-web:4.4.6` and `io.cloudevents:cloudevents-http-vertx:2.3.0` work well with the HTTP Source Connector, the `WebClient` class where HTTP Sink Connector required to introduce does not work with this version.
- In order for the `WebClient` to work properly, `io.cloudevents:cloudevents-http-vertx:2.3.0` needs to be upgraded to `io.cloudevents:cloudevents-http-vertx:3.0.0`.
- `io.clouddevents:clouddevents-http-vertx:3.0.0` and the existing `io.vertx:vertx-web:4.4.6` still do not allow `WebClient` to work properly, and `io.vertx:vertx-web:4.4.6` must be downgraded to `io.vertx:vertx-web:4.3.7` (is this step correct? For most artifacts, higher versions are backwards compatible)

@Fungx May I ask that what do you think of @cnzakii 's dependency conflict?

**Comment by cnzakii** [comment]
@Pil0tXia 

Simply upgrading `io.cloudevents:cloudevents-http-vertx` from version 2.3.0 to 3.0.0 allows the unit tests for the `HttpSourceConnector` to run successfully. However, it doesn't guarantee the absence of other potential conflicts.

![2024-04-14_16 48 37](https://github.com/apache/eventmesh/assets/91261012/15b70c14-2f73-4c83-8c54-5ca48c7798ed)

**Comment by Pil0tXia** [comment]
@cnzakii 

>Therefore, we have two solutions:

Please do both. I've read the release notes of https://github.com/cloudevents/sdk-java, and it seems that there's no breaking change related to vertx between 2.3.0 and 3.0.0.

According to https://vertx.io/docs/vertx-web-client/java/#_using_the_web_client, developers **should** declare their dependencies explicitly. I think the latest version won't have compatibility issues either.

**Comment by cnzakii** [comment]
@Pil0tXia  PTAL
