### ISSUE TITLE
[Question] EventMesh 1.10.0 next版本，发布计划大概是什么时候呢？

### ISSUE THREAD

**Issue by xiaoquanidea** [apache/eventmesh#4841]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

你好，我想问一下，当前您们正在开发的next版本，发布计划大概是什么时候呢？

**Comment by hutiquan** [comment]
> what is your concern?

我想在接下来的业务中使用eventMesh，看到您们在开发新的版本，所以想要去了解一下

**Comment by xiaoquanidea** [comment]
> > > what is your concern?
> > 
> > 
> > 我想在接下来的业务中使用eventMesh，看到您们在开发新的版本，所以想要去了解一下，看能不能跟上最新的版本
> 
> Dashboard is releasing soon, and eventmesh next version is #4816 , may need some time to release.

好的，谢谢解答
