### ISSUE TITLE
[Enhancement] Optimize DeleteTopicProcessor#handler method

### ISSUE THREAD

**Issue by mxsm** [apache/eventmesh#4865]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/15797831/e5f40a4a-49ae-43ed-aa6c-a2ad16c4be97)

### Describe the solution you'd like

1.Because `faildTopic` is a list, calling the `toString` method on it does not fully reflect its content. optimize faildTopic.toString(),
```
sb.append(faildTopic.toString()).append(" not exist in eventmesh");
```
2. remove unnecessary 'toString()' call 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by rohit-satya** [comment]
@mxsm Please assign this to me
