### ISSUE TITLE
[Enhancement] Upgrade pinpoint-profiler to 3.x.x

### ISSUE THREAD

**Issue by Pil0tXia** [apache/eventmesh#4963]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Dependabot failed to upgrade com.navercorp.pinpoint:pinpoint-profiler from 2.4.1 to 2.5.4 in https://github.com/apache/eventmesh/pull/4961. The build failed because there are references to `DefaultTraceRoot` which has been removed.

### Describe the solution you'd like

Update deprecated usages. Upgrade to v3 if possible.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by lmnewton** [comment]
Hi @Pil0tXia , could I take a look at this issue?
