### ISSUE TITLE
[Unit Test] Unit test for HttpConvertsUtils.java

### ISSUE THREAD

**Issue by harshithasudhakar** [apache/eventmesh#4990]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

Add Unit Test for HttpConvertsUtils.java

### Describe the unit tests you want to do

Module name: eventmesh-common
Located at: [eventmesh](https://github.com/apache/eventmesh/tree/master)/[eventmesh-common](https://github.com/apache/eventmesh/tree/master/eventmesh-common)/[src](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src)/[main](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main)/[java](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java)/[org](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org)/[apache](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache)/[eventmesh](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache/eventmesh)/[common](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache/eventmesh/common)/[utils](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache/eventmesh/common/utils)
Task status: ×(unfinished)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by KrispauI** [comment]
Is this task finished?Can I submit a pr for this as my first issue?
