### ISSUE TITLE
[Unit Test] Unit test For LogUtil.java

### ISSUE THREAD

**Issue by harshithasudhakar** [apache/eventmesh#4991]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

Add unit test for LogUtil.java

### Describe the unit tests you want to do

Module name: eventmesh-common
Located at: https://github.com/apache/eventmesh/blob/master/eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/LogUtil.java
Task status: ×(unfinished) 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by melisolmez** [comment]
Hey,This is my first contribute and I want to start with this issue . Could I take on this task and contribute?

**Comment by harshithasudhakar** [comment]
@melisolmez Welcome to the community! Feel free to take it up! :)

**Comment by melisolmez** [comment]
Hello, I wanted to take a look at the tests in the project before working on this issue. But when running the tests Error: Could not find or load main class worker.org.gradle.process.internal.worker.GradleWorkerMain error. I tried to solve it but I couldn't. Do you know the reason for this?
