### ISSUE TITLE
[Unit Test] Unit test for JsonPathUtils.java

### ISSUE THREAD

**Issue by harshithasudhakar** [apache/eventmesh#4992]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

Add unit test for JsonPathUtils.java

### Describe the unit tests you want to do

Module name: eventmesh-common
Located at: https://github.com/apache/eventmesh/blob/master/eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/JsonPathUtils.java
Task status: ×(unfinished) 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by denizOgut** [comment]
Hey, I'm really into unit testing and event-driven design. Could I take on this task and contribute? It feels like the perfect fit for me.

**Comment by denizOgut** [comment]
Hey, opened PR @harshithasudhakar  could you please review ?
