### ISSUE TITLE
[Unit Test] Unit test for HttpRequestUtil.java

### ISSUE THREAD

**Issue by harshithasudhakar** [apache/eventmesh#4994]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

Add Unit test for HttpRequestUtil.java

### Describe the unit tests you want to do

Module name: eventmesh-runtime
Located at: [eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util]
Task status: ×(unfinished)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Abhichede** [comment]
I am willing to contribute here, will raise a PR soon for this.
