### ISSUE TITLE
[Unit Test] Unit test for TraceUtil.java

### ISSUE THREAD

**Issue by harshithasudhakar** [apache/eventmesh#4995]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

Add Unit test for TraceUtil.java

### Describe the unit tests you want to do

Module name: eventmesh-runtime
Located at: https://github.com/apache/eventmesh/blob/master/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/TraceUtils.java
Task status: ×(unfinished)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Abhichede** [comment]
Opened a PR for this, @harshithasudhakar could you review?
