### ISSUE TITLE
[Unit Test] Add test for EtcdCustomService.java

### ISSUE THREAD

**Issue by harshithasudhakar** [apache/eventmesh#5092]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

Add unit test for EtcdCustomService.java

### Describe the unit tests you want to do

Module name: [ eventmesh-meta](https://github.com/apache/eventmesh/tree/master/eventmesh-meta)
Located at: eventmesh-meta/eventmesh-meta-etcd/src/main/java/org/apache/eventmesh/meta/etcd/service/[EtcdCustomService](https://github.com/apache/eventmesh/blob/master/eventmesh-meta/eventmesh-meta-etcd/src/main/java/org/apache/eventmesh/meta/etcd/service/EtcdCustomService.java).java
Task status: ×(unfinished)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by denizOgut** [comment]
Hey, i'm interested in this task. Can you assign this to me please

**Comment by harshithasudhakar** [comment]
Feel free to submit a PR :)

**Comment by YuanG0319tt** [comment]
Hey, i'm interested in this ticket. Was that possible to assign me in this ticket also?
