### ISSUE TITLE
Unify Admin HttpServer into EventMeshHttpserver

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#548]
### Is your enhancement request related to a problem? Please describe
Admin Httpserver in runtime was created in a different way, it is needed to unify it into EventMeshHttpserver.

### Describe the solution you'd like
Add a AdminProcessor in EventMeshHttpServer like AdminMetricsProcessor.

**Comment by silentchildh** [comment]
Whether it can directly use Netty to set up an `EventMeshAdminServer` similar to `EventMeshHttpServer`, and register each `handle` as a `processor`.

**Comment by Pil0tXia** [comment]
Closing as `eventmesh-admin` has been migrated to the eventmesh-dashboard repository, and its design has changed (c.f., https://github.com/apache/eventmesh/issues/4400).
