### ISSUE TITLE
[Enhancement]Unify request handler code style of tcp and http protocol

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#549]
### Is your enhancement request related to a problem? Please describe
Http protocol handle with processors but Tcp protocol handle with tasks, it is needed to unify them into a same code style, it would be better for futher protocol extendtion.

**Comment by silentchildh** [comment]
Could I have a try? I'll try to refactor the TCP code to look like HTTP. 
In addition, I want to optimize the programming style in the HTTP and TCP code during the unification process. For example, more detailed subcontracting and more readable naming.
I think this is appropriately modified and again abstracted in favor of both unification and later expansion.

**Comment by Pil0tXia** [comment]
@silentchildh Welcome, you may submit a PR.

**Comment by silentchildh** [comment]
Thanks, because I want to abstract the coupling logic that exists between HTTP and TCP, I'll open a PR in a few days.
