### ISSUE TITLE
Split the docs by version

### ISSUE THREAD

**Issue by ruanwenjun** [apache/eventmesh#584]
e.g. 1.2.0, 1.3.0 like other project.

![image](https://user-images.githubusercontent.com/22415594/141061946-e962694a-1c29-4a92-ac3b-675ef708a15b.png)

**Comment by qqeasonchen** [comment]
@ruanwenjun good suggestions.

**Comment by xwm1992** [comment]
We can move our docs to the website repository (https://github.com/apache/incubator-eventmesh-site) archive these documents by version, and leave the url in the code repository, which can refer to : https://github.com/apache/incubator-linkis-website

**Comment by Raunak445** [comment]
Hi,
Is this issue still open , if yes then I would like to work upon it.
Its my first time contributing to open source , so can you guide me.
Thanks

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh-site/pull/126.
