### ISSUE TITLE
Do we support event filtering？

### ISSUE THREAD

**Issue by iNanos** [apache/eventmesh#70]

**Comment by ewcchan** [comment]
I would also like to under how it will be supported in EM.

**Comment by qqeasonchen** [comment]
@ewcchan yes, this feature is on our roadmap.

**Comment by ewcchan** [comment]
> @ewcchan yes, this feature is on our roadmap.

Thanks for the info.

**Comment by Pil0tXia** [comment]
Superseded by https://github.com/apache/eventmesh/issues/825 and https://github.com/apache/eventmesh/issues/3263
