### ISSUE TITLE
Wanted: who's using EventMesh

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#8]
Who is Using EventMesh
First of all, thanks sincerely for constantly using and supporting DeFiBus. We will try our best to keep DeFiBus better, and keep growing community and eco-system.

The purpose of this issue
We’d like to listen to the community to make EventMesh better.
We want to attract more people to contribute to EventMesh.
We're willing to learn more EventMesh use scenarios in the field for better planning.
What we expect from you
Pls. submit a comment in this issue to include the following infomation:

your company, school or organization.
your city and country.
your contact info: blog, email, twitter (at least one).
for what business scenario do you use DeFiBus
You can refer to the following sample answer for the format:

* Orgnizatioin: WeBank
* Location: ShenZhen, China
* Contact: chenguangsheng@apache.org
* Purpose: used as cornerstone in distributed service architecture webank switched years ago.
Thanks again for your participation !
EventMesh & DeFiBus Team

谁在使用 EventMesh
首先诚挚地感谢每一位持续关注并使用 DeFiBus的朋友。我们会持续投入，力图把 EventMesh变得更好，把 DeFiBus社区和生态变得更加繁荣。

此 Issue 的目的
聆听社区的声音，让 EventMesh变得更好
吸引更多的人参与贡献
更多的了解 EventMesh的实际使用场景，以方便下一步的规划
我们期待您能提供
在此提交一条评论, 评论内容包括:

您所在公司、学校或组织
您所在的城市、国家
您的联系方式: 微博、邮箱、微信 (至少一个)
您将 EventMesh用于哪些业务场景
您可以参考下面的样例来提供您的信息：

* 组织：微众银行
* 地点：中国深圳
* 联系方式：chenguangsheng@apache.org
* 场景：微众银行内部服务化改造
再次感谢你的参与!!!
EventMesh 团队

**Comment by Pil0tXia** [comment]
Superseded by https://github.com/apache/eventmesh/issues/290
