### ISSUE TITLE
Could we support AMQP protocol?

### ISSUE THREAD

**Issue by xwm1992** [apache/eventmesh#80]

**Comment by qqeasonchen** [comment]
on schedule

**Comment by fighterhit** [comment]
> on schedule

could we support RabbitMQ?

**Comment by xwm1992** [comment]
> could we support RabbitMQ?
ok， you can open a new issue for support RabbitMQ，and we'll have a discussion for this proposal

**Comment by zongtanghu** [comment]
I think we can open serveral issues about the features of EM supporting AMQP Protocol and link those sub-issues in here. @qqeasonchen @wangshaojie4039

**Comment by Pil0tXia** [comment]
We've supported RabbitMQ as a storage-plugin and a connector, and it seems there's no need to implement AMQP in EventMesh's Pub/Sub process. So I will consider this issue as completed.
