### ISSUE TITLE
[Question] Add good first issues

### ISSUE THREAD

**Issue by erdengk** [apache/eventmesh#832]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

I found that the issues with the label good first issue in the issue have been completed. 
I think good first issues are one of the best ways for new contributors to contribute to the community.
If possible, I hope the community adds some good first issues. ：）

**Comment by qqeasonchen** [comment]
@erdengk sure, please keep watching.

**Comment by Pil0tXia** [comment]
We've been working on it, and we appreciate your valuable suggestion. If there are no further details to provide, we consider this issue resolved. Please feel free to reopen it if you have additional information to share.
