### ISSUE TITLE
[Enhancement] Add third-party notice into NOTICE file

### ISSUE THREAD

**Issue by ruanwenjun** [apache/eventmesh#837]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

According to [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0), it's needed to add third-party NOTICE file(if it have) in distribution.

### Describe the solution you'd like

Add NOTICE file in distribution.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
Completed.
