### ISSUE TITLE
[Enhancement] Improve unit test coverage

### ISSUE THREAD

**Issue by xiaoyang-sde** [apache/eventmesh#854]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

The current unit test coverage could be improved to detect potential bugs in the source code.

### Describe the solution you'd like

Write unit tests for the source code to improve unit test coverage.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pil0tXia** [comment]
Superseded by https://github.com/apache/eventmesh/issues/888 #Add unit test code task
