### ISSUE TITLE
[Enhancement] Add test code for this module [eventmesh-admin-rocketmq]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#855]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Add unit test code for eventmesh-admin-rocketmq.

### Describe the solution you'd like

Module name: eventmesh-admin-rocketmq
Located in: eventmesh-admin/eventmesh-admin-rocketmq
Task Status: ×(unfinished) / √(finished)
>Notes: This issue will not be closed, if you want to submit a pr to do some unit tests on this module or select some of the following classes to do some unit tests, please submit a detailed issue separately and linked to the pr you submitted.

| Task Status  | Class | Type |
| :-------------: | :------------- | :------------- |
|   ×  | org/apache/eventmesh/admin/rocketmq/controller/AdminController.java  | controller|
|   ×  | org/apache/eventmesh/admin/rocketmq/handler/TopicsHandler.java  | handler |
|   ×  | org/apache/eventmesh/admin/rocketmq/request/TopicCreateRequest.java | request |
|   ×  | org/apache/eventmesh/admin/rocketmq/response/TopicResponse.java | response |
|   ×  | org/apache/eventmesh/admin/rocketmq/util/JsonUtils.java | utils |
|   ×  | org/apache/eventmesh/admin/rocketmq/util/NetUtils.java | utils |
|   ×  | org/apache/eventmesh/admin/rocketmq/util/RequestMapping.java | utils |
|   ×  | org/apache/eventmesh/admin/rocketmq/util/UrlMappingPattern.java | utils |

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SunnyBoy-WYH** [comment]
Hi! can you assign this good first issue to me? thanks

**Comment by xwm1992** [comment]
> Hi! can you assign this good first issue to me? thanks

OK, welcome~

**Comment by SunnyBoy-WYH** [comment]
您好，我是武跃航，您的邮件我已收到。

**Comment by Alonexc** [comment]
@SunnyBoy-WYH Hello! This issue will not be closed, so you can re submit a detailed issue of this module, and then submit pr and associate it with the issue you proposed.

**Comment by sreenath-tm** [comment]
Hi I would like to contribute to this issue can you let me know how I can solve this issue?

**Comment by Pil0tXia** [comment]
`eventmesh-admin-rocketmq` module has been removed. Closing this issue now.
