### ISSUE TITLE
[Enhancement] Add test code for this module [eventmesh-trace-plugin]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#856]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Add test code for eventmesh-trace-plugin module.

### Describe the solution you'd like

module name: eventmesh-trace-api and eventmesh-trace-zipkin
located in: eventmesh-trace-plugin
Task status: ×(unfinished) / √(finished)

> Notes: This issue will not be closed, if you want to submit a pr to do some unit tests on this module or select some of the following classes to do some unit tests, please submit a detailed issue separately and linked to the pr you submitted.

| Task Status | Class | Type|
| :------: | :------| :------|
| × | org/apache/eventmesh/trace/api/config/ExporterConfiguration.java | config |
| × | org/apache/eventmesh/trace/api/TracePluginFactory.java | service |
| × | org/apache/eventmesh/trace/zipkin/config/ZipkinConfiguration.java | config |

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by HoffmanZheng** [comment]
I'd like to work on this. plz assign this to me.

**Comment by Alonexc** [comment]
@HoffmanZheng Hello! This issue will not be deleted,you can provide another detailed issue for your unit test and associate it with the pr you submitted.

**Comment by HoffmanZheng** [comment]
> @HoffmanZheng Hello! This issue will not be deleted,you can provide another detailed issue for your unit test and associate it with the pr you submitted.

little confused here, why do I need another detailed issue ? To document the test code i write? IMO, the test code is already human readable.

**Comment by Alonexc** [comment]
@HoffmanZheng Because an issue will be closed when it is finished, and this issue will not be closed, the unit test module should be able to continuously supplement, so you need to mention another issue.

**Comment by HoffmanZheng** [comment]
A detailed issue #871 added.

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh/issues/871.
