### ISSUE TITLE
[Enhancement] Add test code for this module [eventmesh-metrics-plugin]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#860]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Add test code for eventmesh-metrics-plugin.

### Describe the solution you'd like

Module name: eventmesh-metrics-api and eventmesh-metrics-prometheus
Located in: eventmesh-metrics-plugin/eventmesh-metrics-api,eventmesh-metrics-prometheus
Task status: ×(unfinished) / √(finished)

> Notes: This issue will not be closed, if you want to submit a pr to do some unit tests on this module or select some of the following classes to do some unit tests, please submit a detailed issue separately and linked to the pr you submitted.

| Task Status | Class | Type |
| :-----: | :----- | :----- |
| × | org/apache/eventmesh/metrics/api/model/HttpSummaryMetrics.java | model |
| × | org/apache/eventmesh/metrics/api/model/TcpSummaryMetrics.java | model |
| × | org/apache/eventmesh/metrics/api/MetricsPluginFactory.java | util|
| × | org/apache/eventmesh/metrics/prometheus/PrometheusMetricsRegistry.java | iml |

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sierra41** [comment]
Hello, Do you mind if I get to work on this issue?

**Comment by qqeasonchen** [comment]
> Hello, Do you mind if I get to work on this issue?

Sure ok，you can create an new sub issue and work on it.
