### ISSUE TITLE
[Enhancement] Add test code for this module [eventmesh-connector-rocketmq]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

The test code for this module is a bit sparse,add test code for eventmesh-connector-rocketmq module.

### Describe the solution you'd like

Module name: eventmesh-connector-rocketmq
Located in: eventmesh-connector-plugin/eventmesh-connector-rocketmq
Task status: ×(unfinished) / √(finished)
>Notes: This issue will not be closed, if you want to submit a pr to do some unit tests on this module or select some of the following classes to do some unit tests, please submit a detailed issue separately and linked to the pr you submitted.

| Task Status | Class | Type |
| :-----: | :----- | :----- |
| × | org/apache/eventmesh/connector/rocketmq/admin/command/Command.java | command |
| × | org/apache/eventmesh/connector/rocketmq/admin/command/CreateTopicCommand.java | command |
| × | org/apache/eventmesh/connector/rocketmq/cloudevent/impl/RocketMQBinaryMessageReader.java | iml |
| × | org/apache/eventmesh/connector/rocketmq/cloudevent/impl/RocketMQMessageWriter.java | iml |
| × | org/apache/eventmesh/connector/rocketmq/cloudevent/RocketMQMessageFactory.java | service |
| × | org/apache/eventmesh/connector/rocketmq/config/ClientConfiguration.java | config |
| × | org/apache/eventmesh/connector/rocketmq/consumer/RocketMQConsumerImpl.java | iml |
| × | org/apache/eventmesh/connector/rocketmq/patch/EventMeshConsumeConcurrentlyContext.java | patch |
| × | org/apache/eventmesh/connector/rocketmq/producer/RocketMQProducerImpl.java | producer |
| × | org/apache/eventmesh/connector/rocketmq/utils/CloudEventUtils.java | utils |
| × | org/apache/eventmesh/connector/rocketmq/utils/OMSUtil.java | utils |
| × | org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java | iml |

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by UniKrau** [comment]
Hi @qqeasonchen  @Alonexc 
I would like to pick the tests . Is it ok for you?

**Comment by UniKrau** [comment]
Thanks @xwm1992
