### ISSUE TITLE
[Enhancement] upload eventmesh docker image into apache repo

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh#913]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

As is the docker image was uploaded into docker hub, to be will be needed to be uploaded into apache repo.

### Describe the solution you'd like

upload docker image into apache offcial repo.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zdb11** [comment]
Hello, I would like to do this task.

**Comment by sudarsan2k5** [comment]
@qqeasonchen I would like to work on this issue.

**Comment by hanshal101** [comment]
@qqeasonchen I would like to work on this issue. Can you please guide me .

**Comment by indra057** [comment]
is this issue still opened..if not you can assign me and  i shall fix this.

**Comment by Alonexc** [comment]
@indra057 Welcome to your pr.

**Comment by kartiktayal** [comment]
@Alonexc , can you give me more information about it.
Do we have a separate apache artifactory where we need to push the image or is it apache org under dockerhub.
From a very brief analysis, I believe we will be making changes to this file [https://github.com/apache/eventmesh/blob/master/.github/workflows/build.yaml](url)

If it is a separate artifactory, can you share with me the keys to login and any action, if already present on marketplace which can be used

**Comment by kartiktayal** [comment]
I will pick this up since I see no PR's attached with it, please help me with the above information.

**Comment by kartiktayal** [comment]
@Alonexc, gentle reminder for providing the information asked above.

**Comment by kartiktayal** [comment]
@Alonexc , can I please pick this up if you can provide the above information or am I interpreting something wrong here and we do not require the above information?

**Comment by Pil0tXia** [comment]
> From a very brief analysis, I believe we will be making changes to this file [https://github.com/apache/eventmesh/blob/master/.github/workflows/build.yaml](url)
> 
> If it is a separate artifactory, can you share with me the keys for login and the path if changed for artifactory.

Perhaps you could try skipping the username and password part first, as this is managed by ASF. We will be in touch when we get the information.

Packaging the docker file itself would be helpful.

**Comment by kartiktayal** [comment]
> > From a very brief analysis, I believe we will be making changes to this file [https://github.com/apache/eventmesh/blob/master/.github/workflows/build.yaml](url)
> 
> > 
> 
> > If it is a separate artifactory, can you share with me the keys for login and the path if changed for artifactory.
> 
> 
> 
> Perhaps you could try skipping the username and password part first, as this is managed by ASF. We will be in touch when we get the information.
> 
> 
> 
> Packaging the docker file itself would be helpful.
> 
> 

Thanks for the information. Will try to raise a PR for it as soon as possible
