### ISSUE TITLE
[Doc] Missing properties file in master and develop branch

### ISSUE THREAD

**Issue by kirinzhu** [apache/eventmesh#953]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

There is a missing file _eventmesh-runtime/conf/rocketmq-client.properties_ which is required to deploy eventmesh-runtime in master branch

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwm1992** [comment]
This file is under the `eventmesh-connector-rocketmq` plugin
